(()=>{'use strict';
const $=id=>document.getElementById(id), COURSE='englishos-grace-v7';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function state(){try{return JSON.parse(localStorage.getItem(COURSE)||'{}')}catch{return{}}}
function ctx(){return window.EnglishOSGuided?.getContext?.()||{day:Number(state().day||1),module:'Primeiro contato',moduleIndex:1,phase:'Fundação',level:'A1',goal:'Cumprimentar e se apresentar em uma conversa curta.',target:'My name is Gustavo.',translation:'Meu nome é Gustavo.',cue:'Introduce yourself.'}}
function css(){if($('coachV23Css'))return;const s=document.createElement('style');s.id='coachV23Css';s.textContent=`
body.coach-v23{background:var(--bg)}
/* Navegação principal: produto, não catálogo */
.nav>button:not(.coach-nav){display:none!important}.coach-nav{width:100%;border:0;background:transparent;color:var(--muted);display:flex;align-items:center;gap:11px;padding:11px 12px;border-radius:13px;font:inherit;cursor:pointer;text-align:left}.coach-nav svg{width:20px;height:20px;stroke:currentColor;fill:none;stroke-width:1.8;flex:0 0 auto}.coach-nav b{font-size:.9rem}.coach-nav:hover,.coach-nav.active{background:var(--brand-soft);color:var(--brand)}.coach-nav.active{font-weight:900}.translation-fab{display:none!important}
.coach-more-backdrop{position:fixed;inset:0;background:rgba(9,18,28,.32);backdrop-filter:blur(2px);z-index:2100;opacity:0;pointer-events:none;transition:.2s}.coach-more-backdrop.open{opacity:1;pointer-events:auto}.coach-more-sheet{position:fixed;z-index:2110;left:50%;top:50%;transform:translate(-50%,-47%) scale(.98);width:min(620px,calc(100vw - 28px));max-height:min(76vh,680px);overflow:auto;padding:18px;border:1px solid var(--line);border-radius:24px;background:var(--panel);box-shadow:0 30px 90px rgba(18,35,58,.24);opacity:0;pointer-events:none;transition:.2s}.coach-more-sheet.open{opacity:1;pointer-events:auto;transform:translate(-50%,-50%) scale(1)}.coach-more-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.coach-more-head h3{margin:0}.coach-more-close{width:38px;height:38px;border:0;border-radius:50%;background:var(--panel-2);color:var(--text);cursor:pointer}.coach-more-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.coach-more-item{min-height:92px;border:1px solid var(--line);border-radius:16px;background:var(--panel-2);color:var(--text);padding:12px;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;gap:5px;font:inherit;cursor:pointer;text-align:left}.coach-more-item:hover{border-color:color-mix(in srgb,var(--brand) 40%,var(--line));background:var(--brand-soft)}.coach-more-item span{font-size:1.25rem}.coach-more-item b{font-size:.86rem}.coach-more-item small{color:var(--muted);line-height:1.35}
/* Home de estudo */
.coach-home{max-width:1180px;margin:0 auto}.coach-hero{padding:clamp(22px,4vw,40px)!important;border-radius:26px!important;background:linear-gradient(145deg,color-mix(in srgb,var(--panel) 92%,#dff5ef),var(--panel))!important;display:grid;grid-template-columns:minmax(0,1.35fr) minmax(290px,.65fr);gap:28px;align-items:center}.coach-kicker{font-size:.72rem;letter-spacing:.12em;text-transform:uppercase;font-weight:900;color:var(--brand)}.coach-hero h2{font-size:clamp(2rem,5vw,3.4rem);line-height:1.02;letter-spacing:-.04em;margin:12px 0 14px;max-width:790px}.coach-hero p{font-size:1.05rem;line-height:1.62;color:var(--muted);max-width:760px}.coach-meta{display:flex;gap:8px;flex-wrap:wrap;margin:17px 0}.coach-meta span{padding:7px 10px;border-radius:999px;background:var(--panel-2);color:var(--muted);font-size:.78rem;font-weight:800}.coach-start{min-height:54px;padding:0 22px;border-radius:15px!important;font-size:1rem!important}.coach-side-goal{padding:19px;border:1px solid var(--line);border-radius:20px;background:var(--panel)}.coach-side-goal .day{font-size:2.7rem;font-weight:950;letter-spacing:-.05em}.coach-side-goal h3{margin:4px 0 7px}.coach-side-goal p{font-size:.9rem;margin:0}.coach-plan{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.coach-plan article{padding:17px;border:1px solid var(--line);border-radius:18px;background:var(--panel)}.coach-plan i{display:grid;place-items:center;width:31px;height:31px;border-radius:50%;background:var(--brand-soft);color:var(--brand);font-style:normal;font-weight:950;margin-bottom:10px}.coach-plan h3{font-size:.98rem;margin:0 0 5px}.coach-plan p{font-size:.82rem;color:var(--muted);margin:0;line-height:1.45}.coach-targets{display:grid;grid-template-columns:1.1fr .9fr;gap:14px;margin-top:14px}.coach-target-card{padding:20px!important}.coach-target-card h3{margin:5px 0 12px}.coach-utterance{padding:13px 14px;border-radius:13px;background:var(--panel-2);margin-top:8px}.coach-utterance b{display:block;font-size:1.02rem}.coach-utterance small{display:block;color:var(--muted);margin-top:4px}.coach-rule{display:flex;gap:12px;align-items:flex-start;padding:12px 0;border-bottom:1px solid var(--line)}.coach-rule:last-child{border-bottom:0}.coach-rule strong{display:grid;place-items:center;min-width:30px;height:30px;border-radius:50%;background:var(--brand-soft);color:var(--brand)}.coach-rule b{display:block}.coach-rule small{color:var(--muted);line-height:1.45}
/* Grace Live: aula particular, não cockpit */
#graceLive>.section-heading{margin-bottom:10px}.future-hud{display:none!important}.live2-grid{display:none!important}.live2-stage{background:#0d1821!important;border:1px solid #1d2d3a!important;box-shadow:0 24px 70px rgba(10,22,34,.16)!important;min-height:0!important}.live2-bg{background:radial-gradient(circle at 50% 20%,rgba(64,151,137,.18),transparent 33%),linear-gradient(180deg,#101d27,#0b151e)!important}.live2-top{padding:14px 16px!important;background:transparent!important;border-bottom:0!important}.live2-state{font-size:.9rem!important}.live2-badge{background:rgba(255,255,255,.06)!important;border-color:rgba(255,255,255,.08)!important;font-size:.7rem!important}.future-mode{top:10px!important;right:10px!important}.future-mode button{background:rgba(255,255,255,.06)!important;border:1px solid rgba(255,255,255,.08)!important;color:#dce8ef!important}.live2-presence{min-height:300px!important;padding:8px 20px!important}.live2-portrait.grace3d{width:min(360px,72vw)!important;height:min(390px,47vh)!important;aspect-ratio:auto!important;border-radius:28px!important;background:linear-gradient(180deg,rgba(22,46,55,.72),rgba(8,19,27,.88))!important;border:1px solid rgba(255,255,255,.075)!important;box-shadow:none!important}.grace3d-label{font-size:.56rem!important;letter-spacing:.08em!important;background:rgba(6,17,24,.48)!important}.grace3d-label{color:transparent!important;width:62px}.grace3d-label:after{content:'GRACE';color:#c5efe7;position:absolute;left:9px;top:6px}.grace3d-status,.grace3d-credit{display:none!important}.live2-caption{max-width:780px;width:calc(100% - 28px);margin:8px auto 0!important;padding:17px 18px!important;border-radius:18px!important;background:rgba(18,31,41,.92)!important;border:1px solid rgba(255,255,255,.075)!important;box-shadow:none!important}.live2-caption .who{font-size:.65rem!important;letter-spacing:.08em!important;color:#8ed8ca!important}.live2-caption p{font-size:clamp(1.08rem,2vw,1.3rem)!important;line-height:1.5!important}.live2-caption small{color:#a7bac6!important}.live2-controls{position:sticky!important;bottom:0!important;background:linear-gradient(180deg,rgba(13,24,33,0),#0d1821 32%)!important;padding:18px 16px 17px!important;z-index:8!important}.live2-mic{width:64px!important;height:64px!important;background:#f4faf8!important;color:#0b1a22!important;box-shadow:0 10px 28px rgba(0,0,0,.22)!important}.live2-darkbtn{background:rgba(255,255,255,.055)!important;border-color:rgba(255,255,255,.08)!important;color:#d7e2e8!important}.live2-side{gap:11px!important}.live2-side>.card{box-shadow:none!important}.live2-stats{display:none!important}.future-transcript{border-radius:10px!important;background:rgba(255,255,255,.035)!important;border-color:rgba(255,255,255,.06)!important;font-size:.76rem!important}
/* Esconder sinais de gamificação antigos da home */
#dashboard .metrics-grid,#dashboard .daily-path,#dashboard .dashboard-grid,#dashboard>.section-heading,#translationBanner{display:none!important}
@media(max-width:980px){.coach-hero,.coach-targets{grid-template-columns:1fr}.coach-plan{grid-template-columns:repeat(2,1fr)}}
@media(max-width:820px){
.main-content{padding:10px 10px calc(82px + env(safe-area-inset-bottom))!important}.topbar{display:none!important}.sidebar{position:fixed!important;left:0!important;right:0!important;bottom:0!important;top:auto!important;width:100%!important;height:calc(70px + env(safe-area-inset-bottom))!important;padding:6px 7px calc(6px + env(safe-area-inset-bottom))!important;border:0!important;border-top:1px solid var(--line)!important;background:color-mix(in srgb,var(--panel) 94%,transparent)!important;backdrop-filter:blur(22px)!important;-webkit-backdrop-filter:blur(22px)!important;z-index:2200!important}.brand,.sidebar-card{display:none!important}.nav{display:grid!important;grid-template-columns:repeat(5,1fr)!important;gap:3px!important;height:100%!important;overflow:visible!important}.coach-nav{height:55px!important;display:flex!important;flex-direction:column!important;justify-content:center!important;align-items:center!important;gap:2px!important;padding:4px 1px!important;border-radius:12px!important;text-align:center!important}.coach-nav svg{width:19px;height:19px}.coach-nav b{font-size:.61rem!important;white-space:nowrap}.coach-more-sheet{top:auto;bottom:calc(78px + env(safe-area-inset-bottom));transform:translateX(-50%) translateY(16px);max-height:67vh;border-radius:22px}.coach-more-sheet.open{transform:translateX(-50%) translateY(0)}.coach-more-grid{grid-template-columns:repeat(2,1fr)}.coach-more-item{min-height:78px}.coach-home{padding:2px}.coach-hero{padding:22px 17px!important;border-radius:22px!important}.coach-hero h2{font-size:2rem!important}.coach-hero p{font-size:.93rem}.coach-side-goal{padding:15px}.coach-side-goal .day{font-size:2.2rem}.coach-plan{grid-template-columns:1fr 1fr;gap:7px}.coach-plan article{padding:13px}.coach-targets{grid-template-columns:1fr}.coach-target-card{padding:16px!important}#graceLive>.section-heading{display:none!important}.live2-layout{grid-template-columns:1fr!important}.live2-side{display:none!important}.live2-stage{border-radius:20px!important;min-height:calc(100dvh - 94px - env(safe-area-inset-bottom))!important}.live2-top{padding:12px 86px 9px 12px!important}.live2-badge{display:none!important}.live2-presence{padding:0 8px!important;min-height:230px!important}.live2-portrait.grace3d{width:min(72vw,290px)!important;height:min(36vh,310px)!important;border-radius:22px!important}.live2-caption{width:calc(100% - 16px)!important;margin:5px auto 0!important;padding:13px 14px!important}.live2-caption p{font-size:1rem!important;line-height:1.43!important}.live2-caption small{font-size:.79rem!important}.live2-controls{padding:14px 9px 12px!important;gap:7px!important;flex-wrap:nowrap!important;overflow-x:auto!important;justify-content:center!important}.live2-controls button{min-height:42px!important;font-size:.72rem!important}.live2-mic{min-width:58px!important;width:58px!important;height:58px!important;padding:0!important}.dialogue-coach{margin-top:9px!important}.dialogue-feedback{margin-top:8px!important}
}
@media(max-width:390px){.coach-plan{grid-template-columns:1fr}.coach-more-grid{grid-template-columns:1fr 1fr}.live2-portrait.grace3d{width:min(70vw,270px)!important;height:min(33vh,285px)!important}}
`;document.head.appendChild(s)}
function icon(name){const d={today:'<path d="M4 10.5 12 4l8 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18.5z"/><path d="M9 20v-6h6v6"/>',grace:'<path d="M21 12a8.5 8.5 0 0 1-9 8.5A8.5 8.5 0 1 1 20.5 11"/><path d="M8.5 12.2c.9 1 2 1.5 3.5 1.5s2.6-.5 3.5-1.5"/><path d="M9 9h.01M15 9h.01"/>',course:'<path d="M5 4.5h11.5A2.5 2.5 0 0 1 19 7v13H7.5A2.5 2.5 0 0 1 5 17.5z"/><path d="M5 17.5A2.5 2.5 0 0 1 7.5 15H19"/>',progress:'<path d="M5 19V9m7 10V5m7 14v-7"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>'}[name];return `<svg viewBox="0 0 24 24" aria-hidden="true">${d}</svg>`}
function createHome(){if($('coachHome'))return;const main=document.querySelector('.main-content');if(!main)return;const sec=document.createElement('section');sec.id='coachHome';sec.className='view';main.insertBefore(sec,main.firstChild);renderHome()}
function renderHome(){const root=$('coachHome');if(!root)return;const c=ctx(),d=c.day||1;const t=c.target||'My name is Gustavo.',pt=c.translation||'';root.innerHTML=`<div class="coach-home"><article class="card coach-hero"><div><div class="coach-kicker">SEU INGLÊS EM 6 MESES · DIA ${d}</div><h2>Hoje você vai conversar. Não navegar em um curso.</h2><p>A Grace vai conduzir uma conversa curta, ouvir o que você realmente disser e corrigir apenas o que mais importa para você continuar falando.</p><div class="coach-meta"><span>20–30 min</span><span>fala antes da teoria</span><span>${d<=30?'apoio completo em português':d<=60?'apoio parcial':'imersão progressiva'}</span></div><button class="primary coach-start" id="coachStartSession">Começar conversa com a Grace</button></div><aside class="coach-side-goal"><div class="coach-kicker">FOCO DE HOJE</div><div class="day">${d}</div><h3>${esc(c.module||'Primeiro contato')}</h3><p>${esc(c.goal||'Conduzir uma conversa simples em inglês.')}</p></aside></article><div class="coach-plan"><article><i>1</i><h3>Aquecer</h3><p>A Grace começa com perguntas fáceis para colocar você falando.</p></article><article><i>2</i><h3>Conversar</h3><p>8–10 turnos de diálogo. Você responde; ela reage ao que ouviu.</p></article><article><i>3</i><h3>Corrigir</h3><p>Um erro importante por vez. Sem interromper a conversa a cada palavra.</p></article><article><i>4</i><h3>Fixar</h3><p>A frase que deu trabalho volta depois, em outro contexto.</p></article></div><div class="coach-targets"><article class="card coach-target-card"><div class="coach-kicker">HOJE VOCÊ PRECISA CONSEGUIR</div><h3>Uma pequena vitória real</h3><div class="coach-utterance"><b>${esc(t)}</b>${pt?`<small>${esc(pt)}</small>`:''}</div><div class="coach-utterance"><b>Could you repeat that, please?</b><small>Você pode pedir para a Grace repetir sempre que precisar.</small></div><div class="coach-utterance"><b>I don't understand this word.</b><small>Continuar a conversa é mais importante do que entender tudo.</small></div></article><article class="card coach-target-card"><div class="coach-kicker">REGRA DA GRACE</div><h3>Como ela vai te ensinar</h3><div class="coach-rule"><strong>1</strong><div><b>Ela pergunta; você responde.</b><small>Nada de ficar repetindo a fala dela como exercício principal.</small></div></div><div class="coach-rule"><strong>2</strong><div><b>Ela julga o sentido.</b><small>Se sua frase for compreensível, a conversa continua.</small></div></div><div class="coach-rule"><strong>3</strong><div><b>Ela corrige com propósito.</b><small>Mostra uma versão melhor e explica rapidamente o porquê.</small></div></div></article></div></div>`;$('coachStartSession').onclick=startGrace}
function existingButton(sel){return document.querySelector(sel)}
function openExisting(sel){const b=existingButton(sel);if(b)b.click()}
function openToday(){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='coachHome'));setActive('today');renderHome();if($('todayLabel'))$('todayLabel').textContent='PLANO DE HOJE';if($('pageTitle'))$('pageTitle').textContent='Seu treino de conversação';if($('pageSubtitle'))$('pageSubtitle').textContent='Fale primeiro. A teoria entra quando ela realmente ajuda.';window.scrollTo({top:0,behavior:'smooth'})}
function openGrace(){setActive('grace');const s=$('live2Scenario');if(s)s.value='guided';openExisting('#graceLiveNav')}
function startGrace(){openGrace();setTimeout(()=>{const s=$('live2Scenario');if(s)s.value='guided';window.GraceDialogueCoach?.start?.()},420)}
function openCourse(){setActive('course');openExisting('#guidedPathNav')}
function openProgress(){setActive('progress');openExisting('.nav-button[data-view="reports"]')}
function setActive(key){document.querySelectorAll('.coach-nav').forEach(b=>b.classList.toggle('active',b.dataset.coach===key))}
function navButton(key,label){const b=document.createElement('button');b.type='button';b.className='coach-nav';b.dataset.coach=key;b.innerHTML=`${icon(key)}<b>${label}</b>`;return b}
function createNav(){const nav=document.querySelector('.nav');if(!nav||$('coachTodayNav'))return;const a=navButton('today','Hoje');a.id='coachTodayNav';a.onclick=openToday;const g=navButton('grace','Grace');g.id='coachGraceNav';g.onclick=openGrace;const c=navButton('course','Treino');c.id='coachCourseNav';c.onclick=openCourse;const p=navButton('progress','Progresso');p.id='coachProgressNav';p.onclick=openProgress;const m=navButton('more','Mais');m.id='coachMoreNav';m.onclick=openMore;nav.prepend(a,g,c,p,m)}
const extras=[['diagnostic','Diagnóstico','Descobrir seu ponto de partida'],['pronunciation','Pronúncia','Treinar clareza da fala'],['conversation','Conversa livre','Conversar sem roteiro'],['practice','Prática real','Registrar conversas humanas'],['roadmap','Plano 180 dias','Ver toda a jornada'],['games','Exercícios extras','Atividades opcionais'],['assessment','Avaliações','Checar sua evolução'],['settings','Ajustes','Voz, tema e preferências']];
function createMore(){if($('coachMoreSheet'))return;const back=document.createElement('div');back.id='coachMoreBackdrop';back.className='coach-more-backdrop';back.onclick=closeMore;document.body.appendChild(back);const sh=document.createElement('section');sh.id='coachMoreSheet';sh.className='coach-more-sheet';sh.innerHTML=`<div class="coach-more-head"><div><div class="coach-kicker">RECURSOS</div><h3>Mais opções</h3></div><button class="coach-more-close" id="coachMoreClose">✕</button></div><div class="coach-more-grid">${extras.map(([v,l,d])=>`<button class="coach-more-item" data-open-view="${v}"><span>${v==='pronunciation'?'◉':v==='diagnostic'?'◎':v==='conversation'?'◌':v==='practice'?'↗':v==='roadmap'?'180':v==='assessment'?'✓':v==='settings'?'⚙':'＋'}</span><b>${l}</b><small>${d}</small></button>`).join('')}<button class="coach-more-item" id="coachOpenTranslator"><span>文</span><b>Tradutor</b><small>Ajuda quando você realmente precisar</small></button></div>`;document.body.appendChild(sh);$('coachMoreClose').onclick=closeMore;sh.querySelectorAll('[data-open-view]').forEach(b=>b.onclick=()=>{closeMore();openExisting(`.nav-button[data-view="${b.dataset.openView}"]`)});$('coachOpenTranslator').onclick=()=>{closeMore();$('translationNav')?.click()}}
function openMore(){createMore();$('coachMoreBackdrop').classList.add('open');$('coachMoreSheet').classList.add('open');setActive('more')}
function closeMore(){$('coachMoreBackdrop')?.classList.remove('open');$('coachMoreSheet')?.classList.remove('open')}
function cleanGrace(){const lab=document.querySelector('.grace3d-label');if(lab)lab.setAttribute('aria-label','Grace');const mod=$('live2Module');const c=ctx();if(mod)mod.innerHTML=`<b>${esc(c.module)}</b><small>Objetivo de hoje: ${esc(c.goal)}</small>`;const start=$('live2Start');if(start&&!window.GraceDialogueCoach?.active)start.textContent='Começar conversa'}
function listenNavState(){document.addEventListener('click',e=>{const b=e.target.closest('.nav-button,.translation-nav,.guided-nav,.grace-live-nav');if(!b)return;setTimeout(()=>{if(b.id==='graceLiveNav')setActive('grace');else if(b.id==='guidedPathNav')setActive('course');else if(b.dataset?.view==='reports')setActive('progress');else if(b.dataset?.view==='dashboard')setActive('today');else if(!b.classList.contains('coach-nav'))setActive('more')},20)},true)}
function init(){document.body.classList.add('coach-v23');css();createHome();createNav();createMore();listenNavState();setInterval(cleanGrace,900);setTimeout(openToday,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();