(()=>{'use strict';
const $=id=>document.getElementById(id), METRICS='englishos-coach-progress-v23';let active=false,busy=false,turn=0,history=[],lastSuggestion='',lastSuggestionPt='',lastData=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function ctx(){return window.EnglishOSGuided?.getContext?.()||{day:1,module:'Primeiro contato',moduleIndex:1,level:'A1',goal:'Apresentar-se',grammar:'I am / My name is',target:'My name is Gustavo.',translation:'Meu nome é Gustavo.',cue:'Say your name.'}}
function metrics(){try{return JSON.parse(localStorage.getItem(METRICS)||'{}')}catch{return{}}}
function saveMetrics(d,user){if(!user)return;const m=metrics();m.turns=Number(m.turns||0)+1;m.words=Number(m.words||0)+String(user).trim().split(/\s+/).filter(Boolean).length;m.corrections=Number(m.corrections||0)+(d.correction||d.better_answer?1:0);m.sessions=Number(m.sessions||0)+(d.session_complete?1:0);m.lastDay=ctx().day;m.lastFeedback=d.feedback||'';m.lastCorrection=d.better_answer||d.correction||'';m.history=Array.isArray(m.history)?m.history:[];m.history.push({at:Date.now(),day:ctx().day,user,understood:d.understood!==false,correction:d.better_answer||d.correction||'',focus:d.focus||''});m.history=m.history.slice(-80);localStorage.setItem(METRICS,JSON.stringify(m));if($('live2Turns'))$('live2Turns').textContent=String(m.turns);if($('live2Words'))$('live2Words').textContent=String(m.words);if($('live2Corrections'))$('live2Corrections').textContent=String(m.corrections)}
function style(){if($('dialogueCoachCss'))return;const s=document.createElement('style');s.id='dialogueCoachCss';s.textContent=`
.dialogue-mode .who:after{content:''!important}.dialogue-coach{margin-top:11px;padding:0;border:0;background:transparent;color:#e8f3f6}.dc-turnline{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}.dc-kicker{font-size:.64rem;letter-spacing:.1em;text-transform:uppercase;color:#8dd9cb;font-weight:900}.dc-turn{font-size:.68rem;color:#728e9d}.dc-prompt{padding:13px 14px;border-radius:14px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.07)}.dc-title{font-size:.74rem;color:#9bb1bd;margin-bottom:5px}.dc-answer{font-size:1.08rem;line-height:1.45;color:#fff;font-weight:820}.dc-pt{font-size:.8rem;color:#93a9b5;margin-top:4px}.dc-hint{font-size:.9rem;line-height:1.45;color:#d3e2e8}.dc-actions{display:flex;gap:7px;margin-top:8px;flex-wrap:wrap}.dc-actions button{border:0;background:transparent;color:#8fd7ca;padding:5px 0;cursor:pointer;font:inherit;font-size:.72rem;font-weight:800}.dc-note{font-size:.69rem;color:#6f8794;margin-top:7px}.dc-hidden-answer .dc-answer,.dc-hidden-answer .dc-pt{filter:blur(7px);opacity:.35;user-select:none}.dc-reveal{display:none!important}.dc-hidden-answer .dc-reveal{display:inline!important}.dialogue-feedback{margin:9px 0 0;padding:12px 13px;border-radius:14px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.07);color:#c6d6de;font-size:.82rem;line-height:1.5}.df-top{display:flex;align-items:center;gap:8px}.df-status{font-weight:900;color:#9ce2d5}.df-status.warn{color:#ffc88b}.df-user{color:#859ca8;margin-top:4px}.df-fix{margin-top:9px;padding-top:9px;border-top:1px solid rgba(255,255,255,.065)}.df-fix b{display:block;color:#f0f6f8;font-size:.8rem;margin-bottom:3px}.df-better{color:#fff;font-weight:800;font-size:.95rem}.df-why{color:#91a9b5;margin-top:3px}.dc-complete{padding:14px;border-radius:14px;background:rgba(114,215,190,.08);border:1px solid rgba(114,215,190,.14)}.dc-complete b{display:block;color:#baf0e5;margin-bottom:4px}.dc-complete p{margin:0;color:#9fb6c1;line-height:1.45}.dialogue-thinking{padding:12px 0;color:#86a0ad;font-size:.82rem}@media(max-width:620px){.dc-answer{font-size:1rem}.dialogue-feedback{font-size:.78rem}.dc-prompt{padding:11px 12px}}
`;document.head.appendChild(s)}
function scaffoldLabel(s){return s==='full'?'Resposta de apoio':s==='starter'?'Começo da resposta':s==='cue'?'Uma dica':s==='keywords'?'Palavras-chave':'Sem roteiro'}
function panel(){const cap=document.querySelector('.live2-caption');if(!cap)return null;cap.classList.add('dialogue-mode');let p=$('dialogueCoach');if(!p){p=document.createElement('div');p.id='dialogueCoach';p.className='dialogue-coach';const ft=$('futureTranscript');if(ft)cap.insertBefore(p,ft);else cap.appendChild(p)}return p}
function renderCoach(d){const p=panel();if(!p)return;lastSuggestion=d.suggested_answer||'';lastSuggestionPt=d.suggested_translation||'';if(d.session_complete){p.className='dialogue-coach';p.innerHTML=`<div class="dc-complete"><b>Sessão concluída</b><p>${esc(d.summary||'Você terminou uma conversa curta. O que deu trabalho volta nas próximas sessões.')}</p></div>`;return}const support=d.support||'full';let body='';if((support==='full'||support==='starter')&&lastSuggestion)body=`<div class="dc-prompt"><div class="dc-title">Você pode responder assim</div><div class="dc-answer">${esc(lastSuggestion)}</div>${lastSuggestionPt?`<div class="dc-pt">${esc(lastSuggestionPt)}</div>`:''}</div>`;else if(d.hint)body=`<div class="dc-prompt"><div class="dc-title">Dica</div><div class="dc-hint">${esc(d.hint)}</div></div>`;else body='<div class="dc-prompt"><div class="dc-title">Sua vez</div><div class="dc-hint">Responda com suas próprias palavras.</div></div>';
p.className='dialogue-coach';p.innerHTML=`<div class="dc-turnline"><span class="dc-kicker">SUA VEZ · ${scaffoldLabel(support)}</span><span class="dc-turn">turno ${Math.max(1,turn+1)} de ~9</span></div>${body}${lastSuggestion?`<div class="dc-actions"><button id="dcHear">Ouvir apoio</button><button id="dcHide">Esconder</button><button class="dc-reveal" id="dcReveal">Mostrar</button></div>`:''}<div class="dc-note">Não precisa copiar a frase. Diga do seu jeito; a Grace avalia o sentido.</div>`;if($('dcHear'))$('dcHear').onclick=()=>speak(lastSuggestion);if($('dcHide'))$('dcHide').onclick=()=>p.classList.add('dc-hidden-answer');if($('dcReveal'))$('dcReveal').onclick=()=>p.classList.remove('dc-hidden-answer')}
function feedback(d,user){let f=$('dialogueFeedback');const cap=document.querySelector('.live2-caption');if(!cap)return;if(!f){f=document.createElement('div');f.id='dialogueFeedback';f.className='dialogue-feedback';const p=panel();p?.insertAdjacentElement('beforebegin',f)}if(!user){f.style.display='none';return}const understood=d.understood!==false;const hasFix=Boolean(d.correction||d.better_answer);f.innerHTML=`<div class="df-top"><span class="df-status ${understood?'':'warn'}">${understood?'✓ Entendi você':'↻ Ainda não ficou claro'}</span>${d.feedback?`<span>${esc(d.feedback)}</span>`:''}</div><div class="df-user">Você disse: “${esc(user)}”</div>${hasFix?`<div class="df-fix"><b>Ajuste que mais importa agora</b>${d.correction?`<div>${esc(d.correction)}</div>`:''}${d.better_answer?`<div class="df-better">${esc(d.better_answer)}</div>`:''}${d.why?`<div class="df-why">${esc(d.why)}</div>`:''}</div>`:''}`;f.style.display='block'}
function state(name,text){const st=$('live2Stage');st?.classList.remove('listening','thinking','speaking');if(name)st?.classList.add(name);if($('live2State'))$('live2State').textContent=text||'Sua vez'}
async function speak(text){if(!text)return;state('speaking','Grace falando');try{const voice=$('live2Voice')?.value||'hannah',r=await fetch('/api/tts',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:String(text).slice(0,260),voice})});if(!r.ok)throw Error();const url=URL.createObjectURL(await r.blob()),a=new Audio(url);a.onended=()=>{URL.revokeObjectURL(url);state('',active?'Sua vez':'Pronta')};await a.play()}catch{if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.86;u.onend=()=>state('',active?'Sua vez':'Pronta');speechSynthesis.cancel();speechSynthesis.speak(u)}else state('',active?'Sua vez':'Pronta')}}
async function ask(answer=''){const c=ctx();const r=await fetch('/api/dialogue',{method:'POST',credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({day:c.day,module:c.module,level:c.level,goal:c.goal,grammar:c.grammar,target:c.target,translation:c.translation,cue:c.cue,answer,turn,history:history.slice(-14)})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'A Grace não conseguiu continuar a conversa.');return d}
function addHistory(role,text){if(!text)return;history.push({role,text});history=history.slice(-16)}
function showTutor(d,user=''){lastData=d;const tutor=d.tutor||'Let us continue.';$('live2Caption').textContent=tutor;$('live2Translation').textContent=d.tutor_translation||'';feedback(d,user);renderCoach(d);addHistory('grace',tutor);saveMetrics(d,user);if(d.session_complete){active=false;state('','Sessão concluída');if($('live2Start'))$('live2Start').textContent='Nova conversa'}else state('','Sua vez');speak(tutor)}
async function start(){if(busy)return;busy=true;active=true;turn=0;history=[];lastData=null;state('thinking','Grace preparando sua conversa');$('live2Caption').textContent='Preparando uma conversa no seu nível...';$('live2Translation').textContent='';feedback({},'');const p=panel();if(p)p.innerHTML='<div class="dialogue-thinking">A Grace está escolhendo uma primeira pergunta simples para você começar falando.</div>';try{const d=await ask('');showTutor(d)}catch(e){active=false;state('','Erro');$('live2Caption').textContent=e.message}finally{busy=false}}
async function send(){if(busy||!active)return;const input=$('live2Text'),answer=String(input?.value||'').trim();if(!answer)return;busy=true;if(input)input.value='';turn++;addHistory('user',answer);state('thinking','Grace analisando sua resposta');const p=panel();if(p)p.innerHTML='<div class="dialogue-thinking">Entendendo o que você quis dizer e escolhendo só a correção que mais ajuda agora…</div>';try{const d=await ask(answer);if(d.repeat_needed)turn=Math.max(0,turn-1);showTutor(d,answer)}catch(e){state('','Erro');$('live2Caption').textContent=e.message}finally{busy=false}}
function updateUi(){const scenario=$('live2Scenario');if(!scenario||scenario.value!=='guided')return;const m=$('live2Module'),c=ctx();if(m)m.innerHTML=`<b>${esc(c.module)}</b><small>${esc(c.goal)}</small>`;const b=$('live2Start');if(b)b.textContent=active?'Recomeçar conversa':'Começar conversa';const t=$('live2Text');if(t)t.placeholder='Responda à Grace...'}
function init(){style();setInterval(updateUi,900);document.addEventListener('change',e=>{if(e.target?.id==='live2Scenario'){active=false;turn=0;history=[];feedback({},'');const p=$('dialogueCoach');if(p)p.remove();setTimeout(updateUi,30)}},true);document.addEventListener('click',e=>{if(e.target.closest?.('#live2Start')&&$('live2Scenario')?.value==='guided'){e.preventDefault();e.stopImmediatePropagation();start();return}if(e.target.closest?.('#live2Send')&&$('live2Scenario')?.value==='guided'&&active){e.preventDefault();e.stopImmediatePropagation();send();return}},true);document.addEventListener('keydown',e=>{if(e.target?.id==='live2Text'&&e.key==='Enter'&&!e.shiftKey&&$('live2Scenario')?.value==='guided'&&active){e.preventDefault();e.stopImmediatePropagation();send()}},true);window.GraceDialogueCoach={start,send,get active(){return active},get turn(){return turn},get last(){return lastData}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();