(()=>{'use strict';
const $=id=>document.getElementById(id);let active=false,busy=false,turn=0,history=[],lastSuggestion='',lastSuggestionPt='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function ctx(){return window.EnglishOSGuided?.getContext?.()||{day:1,module:'Primeiro contato',moduleIndex:1,level:'A1',goal:'Apresentar-se',grammar:'I am / My name is',target:'My name is Gustavo.',translation:'Meu nome é Gustavo.',cue:'Say your name.'}}
function style(){if($('dialogueCoachCss'))return;const s=document.createElement('style');s.id='dialogueCoachCss';s.textContent=`
.dialogue-coach{margin-top:12px;padding:14px 15px;border-radius:14px;border:1px solid rgba(120,238,220,.16);background:linear-gradient(135deg,rgba(88,229,205,.075),rgba(102,118,255,.055));color:#dffbf6;position:relative;overflow:hidden}.dialogue-coach:before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:linear-gradient(#7bffe8,#8097ff)}.dialogue-coach .dc-kicker{font-size:.62rem;letter-spacing:.16em;text-transform:uppercase;color:#80e8d6;font-weight:900}.dialogue-coach .dc-title{font-size:.84rem;color:#a9c5d2;margin-top:4px}.dialogue-coach .dc-answer{font-size:1.12rem;line-height:1.45;color:#fff;margin-top:8px;font-weight:800}.dialogue-coach .dc-pt{font-size:.85rem;color:#8eabb9;margin-top:5px}.dialogue-coach .dc-hint{font-size:.86rem;color:#b6cad6;margin-top:8px;padding-top:8px;border-top:1px solid rgba(255,255,255,.07)}.dialogue-coach .dc-note{font-size:.73rem;color:#6e93a5;margin-top:8px}.dialogue-coach .dc-actions{display:flex;gap:7px;margin-top:9px;flex-wrap:wrap}.dialogue-coach .dc-actions button{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.055);color:#d9f5f0;border-radius:999px;padding:6px 10px;cursor:pointer;font:inherit;font-size:.76rem}.dialogue-feedback{margin-top:9px;padding:9px 11px;border-radius:10px;background:rgba(117,139,255,.08);color:#a9c5d7;font-size:.82rem;line-height:1.45}.dialogue-feedback b{color:#dfeaff}.dialogue-progress{display:flex;gap:5px;margin-top:9px}.dialogue-progress i{height:4px;flex:1;border-radius:999px;background:rgba(255,255,255,.08)}.dialogue-progress i.on{background:linear-gradient(90deg,#68e6cf,#748cff)}.dc-hidden-answer .dc-answer,.dc-hidden-answer .dc-pt{filter:blur(7px);user-select:none;opacity:.4}.dc-reveal{display:none!important}.dc-hidden-answer .dc-reveal{display:inline-flex!important}.live2-caption.dialogue-mode .who:after{content:' · conversa guiada';color:#6f95a6;font-weight:600;letter-spacing:0;text-transform:none}@media(max-width:620px){.dialogue-coach .dc-answer{font-size:1rem}}`;
document.head.appendChild(s)}
function scaffoldLabel(s){return s==='full'?'Apoio completo':s==='starter'?'Começo da frase':s==='cue'?'Dica em português':s==='keywords'?'Só palavras-chave':'Sem roteiro'}
function panel(){const cap=document.querySelector('.live2-caption');if(!cap)return null;cap.classList.add('dialogue-mode');let p=$('dialogueCoach');if(!p){p=document.createElement('div');p.id='dialogueCoach';p.className='dialogue-coach';const ft=$('futureTranscript');if(ft)cap.insertBefore(p,ft);else cap.appendChild(p)}return p}
function renderCoach(d){const p=panel();if(!p)return;lastSuggestion=d.suggested_answer||'';lastSuggestionPt=d.suggested_translation||'';const support=d.support||'full',has=lastSuggestion||d.hint;let body='';if(support==='full'||support==='starter')body=`<div class="dc-answer">${esc(lastSuggestion||'Responda com suas próprias palavras.')}</div>${lastSuggestionPt?`<div class="dc-pt">${esc(lastSuggestionPt)}</div>`:''}`;else if(d.hint)body=`<div class="dc-hint"><b>Dica:</b> ${esc(d.hint)}</div>`;else body='<div class="dc-hint">Agora responda sem roteiro. A Grace continua ajudando apenas quando houver necessidade.</div>';
p.className='dialogue-coach';p.innerHTML=`<div class="dc-kicker">SUA VEZ · ${scaffoldLabel(support)}</div><div class="dc-title">Você pode responder assim — não precisa copiar palavra por palavra.</div>${body}${has&&lastSuggestion?`<div class="dc-actions"><button id="dcHear">🔊 Ouvir sugestão</button><button id="dcHide">◌ Esconder resposta</button><button class="dc-reveal" id="dcReveal">◉ Mostrar resposta</button></div>`:''}<div class="dc-note">Fale naturalmente. Se sua resposta tiver o mesmo sentido, a Grace aceita e continua.</div><div class="dialogue-progress">${Array.from({length:5},(_,i)=>`<i class="${i<=Math.min(4,Math.floor(turn/2))?'on':''}"></i>`).join('')}</div>`;
if($('dcHear'))$('dcHear').onclick=()=>speak(lastSuggestion);if($('dcHide'))$('dcHide').onclick=()=>p.classList.add('dc-hidden-answer');if($('dcReveal'))$('dcReveal').onclick=()=>p.classList.remove('dc-hidden-answer')}
function feedback(d,user){let f=$('dialogueFeedback');const cap=document.querySelector('.live2-caption');if(!cap)return;if(!f){f=document.createElement('div');f.id='dialogueFeedback';f.className='dialogue-feedback';const p=panel();p?.insertAdjacentElement('beforebegin',f)}const parts=[];if(user)parts.push(`<b>Você:</b> ${esc(user)}`);if(d.feedback)parts.push(esc(d.feedback));if(d.correction)parts.push(`<b>Ajuste:</b> ${esc(d.correction)}`);f.innerHTML=parts.join('<br>');f.style.display=parts.length?'block':'none'}
function state(name,text){const st=$('live2Stage');st?.classList.remove('listening','thinking','speaking');if(name)st?.classList.add(name);if($('live2State'))$('live2State').textContent=text||'Sua vez'}
async function speak(text){if(!text)return;state('speaking','Grace está falando');try{const voice=$('live2Voice')?.value||'hannah',r=await fetch('/api/tts',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:String(text).slice(0,200),voice})});if(!r.ok)throw Error();const url=URL.createObjectURL(await r.blob()),a=new Audio(url);a.onended=()=>{URL.revokeObjectURL(url);state('','Sua vez')};await a.play()}catch{if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.86;u.onend=()=>state('','Sua vez');speechSynthesis.cancel();speechSynthesis.speak(u)}else state('','Sua vez')}}
async function ask(answer=''){const c=ctx();const r=await fetch('/api/dialogue',{method:'POST',credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({day:c.day,module:c.module,level:c.level,goal:c.goal,grammar:c.grammar,target:c.target,translation:c.translation,cue:c.cue,answer,turn,history:history.slice(-10)})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'A Grace não conseguiu continuar o diálogo.');return d}
function addHistory(role,text){if(!text)return;history.push({role,text});history=history.slice(-12)}
function showTutor(d,user=''){const tutor=d.tutor||'Good. Let us continue.';$('live2Caption').textContent=tutor;$('live2Translation').textContent=d.tutor_translation||'';feedback(d,user);renderCoach(d);addHistory('grace',tutor);speak(tutor)}
async function start(){if(busy)return;busy=true;active=true;turn=0;history=[];state('thinking','Grace preparando a conversa');$('live2Caption').textContent='...';$('live2Translation').textContent='';const old=$('dialogueFeedback');if(old)old.style.display='none';try{const d=await ask('');showTutor(d)}catch(e){state('','Erro');$('live2Caption').textContent=e.message}finally{busy=false}}
async function send(){if(busy)return;const input=$('live2Text'),answer=String(input?.value||'').trim();if(!answer)return;busy=true;if(input)input.value='';turn++;addHistory('user',answer);state('thinking','Grace entendeu. Preparando resposta');const p=panel();if(p)p.innerHTML='<div class="dc-kicker">GRACE ESTÁ RESPONDENDO</div><div class="dc-title">Sua resposta foi recebida. O diálogo vai continuar, não voltar para repetição.</div>';try{const d=await ask(answer);showTutor(d,answer)}catch(e){state('','Erro');$('live2Caption').textContent=e.message}finally{busy=false}}
function updateUi(){const scenario=$('live2Scenario');if(!scenario||scenario.value!=='guided')return;const m=$('live2Module'),c=ctx();if(m)m.innerHTML=`<b>Módulo ${c.moduleIndex}: ${esc(c.module)}</b><small>Diálogo guiado · a Grace pergunta e você responde com apoio progressivo.</small>`;const b=$('live2Start');if(b)b.textContent=active?'↻ Reiniciar diálogo':'▶ Começar diálogo';const t=$('live2Text');if(t)t.placeholder='Responda à Grace com suas próprias palavras...'}
function init(){style();setInterval(updateUi,800);document.addEventListener('change',e=>{if(e.target?.id==='live2Scenario'){active=false;turn=0;history=[];const p=$('dialogueCoach');if(p)p.remove();const f=$('dialogueFeedback');if(f)f.remove();setTimeout(updateUi,20)}},true);document.addEventListener('click',e=>{if(e.target.closest?.('#live2Start')&&$('live2Scenario')?.value==='guided'){e.preventDefault();e.stopImmediatePropagation();start();return}if(e.target.closest?.('#live2Send')&&$('live2Scenario')?.value==='guided'&&active){e.preventDefault();e.stopImmediatePropagation();send();return}},true);document.addEventListener('keydown',e=>{if(e.target?.id==='live2Text'&&e.key==='Enter'&&!e.shiftKey&&$('live2Scenario')?.value==='guided'&&active){e.preventDefault();e.stopImmediatePropagation();send()}},true);window.GraceDialogueCoach={start,send}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();