(()=>{'use strict';
const $=id=>document.getElementById(id), COURSE='englishos-grace-v7', PREF='englishos-translation-preference', LIVE='englishos-grace-live-v1', VOICE='englishos-grace-live-voice';
let history=[], recorder=null, chunks=[], stream=null, recordingTimer=null, recordingStarted=0, lastReply='', sessionWords=0, turns=0, corrections=0, speakingAudio=null;
const scenarios={
  meeting:{label:'Reunião de projeto',role:'Project stakeholder',opening:'Good evening, Gustavo. Please give me a short project status update. What is on track, and what needs attention?'},
  interview:{label:'Entrevista internacional',role:'International recruiter',opening:'Hello, Gustavo. It is great to meet you. Could you introduce yourself and summarize your leadership experience?'},
  client:{label:'Cliente internacional',role:'International client',opening:'Hi, Gustavo. I am concerned about the delivery date. Can you explain the current situation and the next actions?'},
  technology:{label:'Tecnologia e AWS',role:'Solutions architect',opening:'Let us review the solution. Can you explain the architecture and its main business benefit?'},
  daily:{label:'Conversação do dia a dia',role:'English teacher',opening:'Hi, Gustavo. How was your day? Tell me one good thing and one difficult thing that happened.'},
  biblical:{label:'Bíblia e teologia',role:'Bible study partner',opening:'Hello, Gustavo. What Bible passage has encouraged or challenged you recently, and why?'}
};
const readState=()=>{try{return JSON.parse(localStorage.getItem(COURSE)||'{}')}catch{return{}}};
const day=()=>Math.max(1,Math.min(180,Number(readState().day||1)));
const translationMode=()=>{const p=localStorage.getItem(PREF)||'auto';if(p!=='auto')return p;return day()<=30?'full':day()<=60?'guided':'off'};
const helpLevel=()=>translationMode()==='full'?'high':translationMode()==='guided'?'medium':'low';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function styles(){if($('graceLiveStyles'))return;const s=document.createElement('style');s.id='graceLiveStyles';s.textContent=`
.grace-live-nav{border:0;background:linear-gradient(135deg,color-mix(in srgb,var(--brand) 12%,transparent),color-mix(in srgb,var(--brand-2) 10%,transparent));color:var(--text);display:flex;align-items:center;gap:10px;padding:11px 12px;border-radius:12px;text-align:left;width:100%;font:inherit;cursor:pointer}.grace-live-nav:hover,.grace-live-nav.active{background:linear-gradient(135deg,var(--brand-soft),color-mix(in srgb,var(--brand-2) 14%,var(--panel)))}
.live-layout{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.7fr);gap:16px;align-items:start}.live-stage{min-height:650px;padding:0!important;overflow:hidden;position:relative;background:radial-gradient(circle at 50% 16%,rgba(117,170,255,.28),transparent 30%),linear-gradient(160deg,#edf8ff,#f8fcff 55%,#e9f7f3)}[data-theme=dark] .live-stage{background:radial-gradient(circle at 50% 16%,rgba(117,170,255,.18),transparent 30%),linear-gradient(160deg,#13243a,#182d45)}
.live-top{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--panel) 84%,transparent);backdrop-filter:blur(12px)}.live-state{display:flex;align-items:center;gap:9px;font-weight:900}.live-state-dot{width:11px;height:11px;border-radius:50%;background:#94a3b8;box-shadow:0 0 0 5px rgba(148,163,184,.15)}.live-stage.is-listening .live-state-dot{background:#ef4444;box-shadow:0 0 0 6px rgba(239,68,68,.14);animation:livePulse .8s infinite alternate}.live-stage.is-thinking .live-state-dot{background:#f59e0b;box-shadow:0 0 0 6px rgba(245,158,11,.14);animation:livePulse .8s infinite alternate}.live-stage.is-speaking .live-state-dot{background:#22c55e;box-shadow:0 0 0 6px rgba(34,197,94,.14);animation:livePulse .55s infinite alternate}@keyframes livePulse{to{transform:scale(1.2)}}
.avatar-zone{display:grid;place-items:center;padding:30px 20px 12px;min-height:335px}.grace-person{position:relative;width:230px;height:280px;display:grid;place-items:end center}.grace-halo{position:absolute;left:50%;top:22px;width:205px;height:205px;transform:translateX(-50%);border-radius:50%;background:radial-gradient(circle,rgba(67,213,180,.18),rgba(117,170,255,.10) 55%,transparent 70%);animation:halo 3s ease-in-out infinite alternate}@keyframes halo{to{transform:translateX(-50%) scale(1.07)}}
.grace-body{position:absolute;bottom:0;width:180px;height:112px;border-radius:80px 80px 22px 22px;background:linear-gradient(145deg,#173c5a,#295f78);box-shadow:0 24px 45px rgba(31,79,110,.22)}.grace-neck{position:absolute;bottom:96px;width:48px;height:45px;border-radius:20px;background:#c98968}.grace-head{position:absolute;bottom:116px;width:142px;height:166px;border-radius:46% 46% 44% 44%;background:linear-gradient(145deg,#e7b18e,#c98262);box-shadow:0 14px 35px rgba(63,55,50,.18);overflow:hidden}.grace-hair{position:absolute;inset:-14px -12px auto;height:88px;border-radius:50% 50% 36% 36%;background:linear-gradient(145deg,#342622,#594035)}.grace-hair:before,.grace-hair:after{content:'';position:absolute;top:43px;width:25px;height:96px;background:#49342e;border-radius:20px}.grace-hair:before{left:0;transform:rotate(6deg)}.grace-hair:after{right:0;transform:rotate(-6deg)}
.eye{position:absolute;top:77px;width:13px;height:7px;border-radius:50%;background:#2a2523;animation:blink 5s infinite}.eye.left{left:39px}.eye.right{right:39px}@keyframes blink{0%,46%,50%,100%{transform:scaleY(1)}48%{transform:scaleY(.08)}}.brow{position:absolute;top:64px;width:25px;height:4px;border-radius:10px;background:#6f4939}.brow.left{left:31px;transform:rotate(-5deg)}.brow.right{right:31px;transform:rotate(5deg)}.nose{position:absolute;top:88px;left:67px;width:9px;height:22px;border-radius:10px;border-right:2px solid rgba(111,65,48,.32)}.mouth{position:absolute;left:50%;top:120px;width:32px;height:8px;transform:translateX(-50%);border-radius:0 0 20px 20px;background:#8d3e45;transition:.15s}.live-stage.is-speaking .mouth{animation:talk .22s infinite alternate}@keyframes talk{from{height:7px;width:30px;border-radius:0 0 18px 18px}to{height:21px;width:24px;border-radius:50%}}.cheek{position:absolute;top:100px;width:20px;height:10px;border-radius:50%;background:rgba(211,94,92,.12)}.cheek.left{left:23px}.cheek.right{right:23px}
.live-name{text-align:center;margin-top:10px}.live-name strong{display:block;font-size:1.35rem}.live-name span{color:var(--muted);font-size:.88rem}.caption-wrap{padding:0 18px 18px}.live-caption{min-height:78px;border:1px solid var(--line);background:color-mix(in srgb,var(--panel) 91%,transparent);border-radius:18px;padding:15px 17px;font-size:1.05rem;line-height:1.55;box-shadow:var(--shadow)}.live-translation{margin-top:8px;color:var(--muted);font-size:.93rem;padding-left:3px}.live-correction{margin-top:9px;border-left:4px solid var(--brand-2);padding:9px 11px;background:var(--panel-2);border-radius:9px;color:var(--muted)}
.live-controls{display:flex;justify-content:center;align-items:center;gap:10px;padding:0 18px 22px;flex-wrap:wrap}.live-mic{width:76px;height:76px;border:0;border-radius:50%;background:linear-gradient(135deg,var(--brand),var(--brand-2));color:#fff;font-size:1.8rem;box-shadow:0 13px 35px rgba(32,102,132,.26);cursor:pointer}.live-mic.recording{background:linear-gradient(135deg,#d9364f,#f05e64);animation:livePulse .65s infinite alternate}.live-side{display:grid;gap:16px}.live-side .card h3{margin-top:5px}.live-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.live-metric{padding:11px;border-radius:12px;background:var(--panel-2);text-align:center}.live-metric strong{display:block;font-size:1.25rem}.live-metric small{color:var(--muted)}.live-history{display:grid;gap:8px;max-height:260px;overflow:auto}.live-turn{padding:10px 11px;border-radius:11px;background:var(--panel-2);font-size:.88rem}.live-turn.user{border-left:3px solid var(--brand-2)}.live-turn.grace{border-left:3px solid var(--brand)}.live-text-row{display:flex;gap:8px}.live-text-row textarea{min-height:82px}.live-pill{display:inline-flex;padding:6px 9px;border-radius:999px;background:var(--brand-soft);color:var(--brand);font-size:.78rem;font-weight:900}
@media(max-width:1000px){.live-layout{grid-template-columns:1fr}.live-stage{min-height:600px}}@media(max-width:650px){.grace-person{transform:scale(.88);margin:-10px}.avatar-zone{min-height:300px}.live-mic{width:68px;height:68px}.live-top{align-items:flex-start;gap:8px;flex-direction:column}.live-metrics{grid-template-columns:repeat(3,1fr)}}`;
document.head.appendChild(s)}
function nav(){if($('graceLiveNav'))return;const n=document.querySelector('.nav');if(!n)return;const b=document.createElement('button');b.id='graceLiveNav';b.className='grace-live-nav';b.type='button';b.innerHTML='<span>🗣️</span><b>Grace Live</b>';const conv=n.querySelector('[data-view="conversation"]');conv?.insertAdjacentElement('afterend',b);if(!conv)n.appendChild(b);b.onclick=openLive}
function view(){if($('graceLive'))return;const main=document.querySelector('.main-content');if(!main)return;const sec=document.createElement('section');sec.id='graceLive';sec.className='view';sec.innerHTML=`
<div class="section-heading"><div><div class="eyebrow">AULA AO VIVO COM IA</div><h2>Converse com a Grace olhando para você</h2><p>Escute, responda por voz, receba correção e continue a conversa sem sair da aula.</p></div><span class="status-pill" id="liveProvider">Grace Live</span></div>
<div class="live-layout"><article class="card live-stage" id="liveStage"><div class="live-top"><div class="live-state"><span class="live-state-dot"></span><span id="liveStateText">Pronta para começar</span></div><span class="live-pill" id="liveHelpBadge">Ajuda bilíngue</span></div>
<div class="avatar-zone"><div><div class="grace-person"><div class="grace-halo"></div><div class="grace-body"></div><div class="grace-neck"></div><div class="grace-head"><div class="grace-hair"></div><i class="brow left"></i><i class="brow right"></i><i class="eye left"></i><i class="eye right"></i><i class="nose"></i><i class="cheek left"></i><i class="cheek right"></i><i class="mouth"></i></div></div><div class="live-name"><strong>Grace</strong><span id="liveRole">Sua professora particular</span></div></div></div>
<div class="caption-wrap"><div class="live-caption" id="liveCaption">Escolha um cenário e clique em <b>Iniciar aula</b>.</div><div class="live-translation" id="liveTranslation"></div><div class="live-correction hidden" id="liveCorrection"></div></div>
<div class="live-controls"><button class="secondary" id="liveStart">▶ Iniciar aula</button><button class="live-mic" id="liveMic" title="Responder por voz">🎙️</button><button class="secondary" id="liveRepeat">🔊 Repetir</button><button class="ghost" id="liveEnd">Encerrar</button></div></article>
<aside class="live-side"><article class="card"><div class="eyebrow">CENÁRIO</div><h3>O que vamos treinar?</h3><select id="liveScenario">${Object.entries(scenarios).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}</select><label class="field-label">Voz da Grace</label><select id="liveVoice"><option value="hannah">Hannah — natural</option><option value="autumn">Autumn — acolhedora</option><option value="diana">Diana — clara</option></select><label class="field-label">Apoio</label><div class="info-box" id="liveHelpText"></div><div class="button-row"><button class="secondary" id="liveToggleTranslation">🌐 Tradução</button><button class="secondary" id="liveToggleAutoSpeak">🔊 Voz automática: ON</button></div></article>
<article class="card"><div class="eyebrow">SESSÃO</div><div class="live-metrics"><div class="live-metric"><strong id="liveTurns">0</strong><small>respostas</small></div><div class="live-metric"><strong id="liveWords">0</strong><small>palavras</small></div><div class="live-metric"><strong id="liveCorrections">0</strong><small>correções</small></div></div></article>
<article class="card"><div class="eyebrow">DIGITAR TAMBÉM FUNCIONA</div><div class="live-text-row"><textarea id="liveText" placeholder="Digite sua resposta em inglês..."></textarea></div><button class="primary full" id="liveSendText">Enviar para Grace</button></article>
<article class="card"><div class="eyebrow">ÚLTIMAS FALAS</div><div class="live-history" id="liveHistory"><p>Nenhuma fala ainda.</p></div></article></aside></div>`;
const settings=$('settings');main.insertBefore(sec,settings||null);bind()}
function openLive(){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='graceLive'));document.querySelectorAll('.nav-button,.translation-nav,.grace-live-nav').forEach(b=>b.classList.remove('active'));$('graceLiveNav')?.classList.add('active');if($('todayLabel'))$('todayLabel').textContent='GRACE LIVE';if($('pageTitle'))$('pageTitle').textContent='Aula ao vivo com a Grace';if($('pageSubtitle'))$('pageSubtitle').textContent='Fale em inglês e deixe a Grace conduzir a conversa.';updateHelp();window.scrollTo({top:0,behavior:'smooth'})}
function setState(state,text){const stage=$('liveStage');stage?.classList.remove('is-listening','is-thinking','is-speaking');if(state)stage?.classList.add(`is-${state}`);if($('liveStateText'))$('liveStateText').textContent=text||({listening:'Ouvindo você...',thinking:'Grace está pensando...',speaking:'Grace está falando...'}[state]||'Pronta')}
function updateHelp(){const m=translationMode(),d=day();if($('liveHelpBadge'))$('liveHelpBadge').textContent=m==='full'?'Tradução completa':m==='guided'?'Tradução sob demanda':'Imersão assistida';if($('liveHelpText'))$('liveHelpText').textContent=m==='full'?`Dia ${d}: inglês + tradução e explicações em português.`:m==='guided'?`Dia ${d}: inglês primeiro; tradução quando ajudar na compreensão.`:`Dia ${d}: inglês como padrão; tradução continua disponível.`}
function recordCourseTurn(words){try{const s=readState();s.conversations=Number(s.conversations||0)+1;s.xp=Number(s.xp||0)+8;s.skills=s.skills||{};s.skills.speaking=Math.min(100,Number(s.skills.speaking||0)+1);localStorage.setItem(COURSE,JSON.stringify(s))}catch{}}
function saveLive(){try{localStorage.setItem(LIVE,JSON.stringify({history:history.slice(-30),sessionWords,turns,corrections}))}catch{}}
function renderHistory(){const box=$('liveHistory');if(!box)return;const items=history.slice(-8);box.innerHTML=items.length?items.map(x=>`<div class="live-turn ${x.role}"><b>${x.role==='user'?'Você':'Grace'}</b><br>${esc(x.text)}</div>`).join(''):'<p>Nenhuma fala ainda.</p>';box.scrollTop=box.scrollHeight;$('liveTurns').textContent=turns;$('liveWords').textContent=sessionWords;$('liveCorrections').textContent=corrections}
function scenario(){return scenarios[$('liveScenario')?.value||'meeting']||scenarios.meeting}
function translationVisible(){return $('liveToggleTranslation')?.dataset.on!=='0'}
function autoSpeak(){return $('liveToggleAutoSpeak')?.dataset.on!=='0'}
function splitSpeech(text){const t=String(text||'').replace(/\s+/g,' ').trim();if(t.length<=180)return[t];const parts=[];let rest=t;while(rest.length){if(rest.length<=180){parts.push(rest);break}let cut=Math.max(rest.lastIndexOf('. ',180),rest.lastIndexOf('? ',180),rest.lastIndexOf('! ',180));if(cut<80)cut=rest.lastIndexOf(' ',180);if(cut<40)cut=180;parts.push(rest.slice(0,cut+1).trim());rest=rest.slice(cut+1).trim()}return parts}
async function browserSpeak(text,rate=.86){return new Promise(resolve=>{if(!('speechSynthesis'in window))return resolve();speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=rate;const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/en-US/i.test(v.lang)&&/zira|samantha|aria|jenny|female/i.test(v.name))||vs.find(v=>/en-US/i.test(v.lang))||null;u.onend=resolve;u.onerror=resolve;speechSynthesis.speak(u)})}
async function speakGrace(text){if(!text)return;lastReply=text;setState('speaking','Grace está falando...');try{for(const part of splitSpeech(text)){const r=await fetch('/api/tts',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:part,voice:$('liveVoice')?.value||'hannah'})});if(!r.ok)throw Error('tts');const blob=await r.blob();const url=URL.createObjectURL(blob);await new Promise(resolve=>{const a=new Audio(url);speakingAudio=a;a.onended=()=>{URL.revokeObjectURL(url);resolve()};a.onerror=()=>{URL.revokeObjectURL(url);resolve()};a.play().catch(resolve)});}}catch{await browserSpeak(text)}finally{speakingAudio=null;setState('', 'Sua vez. Responda em inglês.')}
}
function showGrace(ai){const reply=ai?.reply||ai?.next_question||'Tell me more, please.';lastReply=reply;$('liveCaption').textContent=reply;const tr=translationVisible()?(ai?.translation||''):'';$('liveTranslation').textContent=tr?`🇧🇷 ${tr}`:'';const corr=[ai?.correction,ai?.explanation].filter(Boolean).join(' — ');const c=$('liveCorrection');if(corr){corrections++;c.classList.remove('hidden');c.innerHTML=`<b>Correção da Grace:</b> ${esc(corr)}`}else{c.classList.add('hidden');c.textContent=''};history.push({role:'grace',text:reply});renderHistory();saveLive();if(autoSpeak())speakGrace(reply);else setState('', 'Sua vez. Responda em inglês.')}
async function waitAI(){for(let i=0;i<80;i++){if(window.GraceAI?.ask)return true;await new Promise(r=>setTimeout(r,100))}return false}
async function sendUser(text){const clean=String(text||'').trim();if(!clean)return;history.push({role:'user',text:clean});turns++;const wc=clean.split(/\s+/).filter(Boolean).length;sessionWords+=wc;recordCourseTurn(wc);renderHistory();$('liveCaption').textContent=clean;$('liveTranslation').textContent='';$('liveCorrection').classList.add('hidden');setState('thinking','Grace está pensando...');if(!await waitAI()){setState('', 'Grace ainda está carregando.');return}const sc=scenario();const ai=await window.GraceAI.ask('conversation',{message:clean,scenario:$('liveScenario').value,scenario_role:sc.role,help:helpLevel(),history:history.slice(-12).map(x=>({role:x.role==='grace'?'assistant':'user',text:x.text})),level:readState().diagnostic?.level||'Inicial',day:day(),translation_mode:translationMode(),profile:{name:'Gustavo',background:'Gerente de projetos, Agile Coach e líder de tecnologia com mais de 17 anos de experiência.',goal:'Inglês profissional funcional para liderança, tecnologia, AWS, entrevistas, clientes e Bíblia.'}});if(!ai){setState('',window.GraceAI.getStatus?.().lastError||'A Grace não respondeu.');$('liveCaption').textContent='Não consegui falar com a Grace agora. Use o teste de conexão em /api/probe.';return}showGrace(ai)}
async function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=reject;r.readAsDataURL(blob)})}
async function startRecording(){if(recorder?.state==='recording')return stopRecording();try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});chunks=[];const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';recorder=new MediaRecorder(stream,{mimeType:mime});recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=processRecording;recorder.start();recordingStarted=Date.now();$('liveMic').classList.add('recording');$('liveMic').textContent='■';setState('listening','Ouvindo você... clique novamente para enviar.');recordingTimer=setTimeout(stopRecording,25000)}catch{setState('', 'Não consegui acessar o microfone.');$('liveCaption').textContent='Permita o uso do microfone no navegador para conversar por voz.'}}
function stopRecording(){clearTimeout(recordingTimer);if(recorder?.state==='recording')recorder.stop();$('liveMic')?.classList.remove('recording');if($('liveMic'))$('liveMic').textContent='🎙️'}
async function processRecording(){stream?.getTracks().forEach(t=>t.stop());stream=null;const blob=new Blob(chunks,{type:recorder?.mimeType||'audio/webm'});if(blob.size<1000){setState('', 'Não ouvi uma resposta. Tente novamente.');return}setState('thinking','Transcrevendo sua fala com Whisper...');try{const base64=await blobToBase64(blob);const r=await fetch('/api/stt',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({audioBase64:base64,mimeType:blob.type})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Não consegui entender o áudio.');if(!d.text)throw Error('Não ouvi palavras suficientes.');await sendUser(d.text)}catch(e){setState('', 'Falha ao entender sua fala.');$('liveCaption').textContent=e.message}}
function startLesson(){history=[];sessionWords=0;turns=0;corrections=0;renderHistory();const sc=scenario();$('liveRole').textContent=sc.role;$('liveCaption').textContent=sc.opening;$('liveTranslation').textContent=translationMode()==='full'?'🇧🇷 A Grace vai falar em inglês; você pode acompanhar a tradução e responder por voz.':'';$('liveCorrection').classList.add('hidden');history.push({role:'grace',text:sc.opening});renderHistory();saveLive();if(autoSpeak())speakGrace(sc.opening);else setState('', 'Sua vez. Responda em inglês.')}
function endLesson(){stopRecording();speakingAudio?.pause?.();speechSynthesis?.cancel?.();setState('', 'Sessão encerrada.');$('liveCaption').textContent=`Sessão encerrada: ${turns} resposta(s) e ${sessionWords} palavra(s) faladas.`;$('liveTranslation').textContent='';saveLive()}
function bind(){if($('liveStart')?.dataset.bound)return;$('liveStart').dataset.bound='1';$('liveStart').onclick=startLesson;$('liveMic').onclick=startRecording;$('liveRepeat').onclick=()=>lastReply&&browserSpeak(lastReply,.68);$('liveEnd').onclick=endLesson;$('liveSendText').onclick=()=>{const t=$('liveText').value.trim();if(t){$('liveText').value='';sendUser(t)}};$('liveText').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('liveSendText').click()}};$('liveScenario').onchange=()=>{$('liveRole').textContent=scenario().role};$('liveVoice').value=localStorage.getItem(VOICE)||'hannah';$('liveVoice').onchange=e=>localStorage.setItem(VOICE,e.target.value);$('liveToggleTranslation').dataset.on=translationMode()==='off'?'0':'1';$('liveToggleTranslation').onclick=()=>{const b=$('liveToggleTranslation'),on=b.dataset.on!=='0';b.dataset.on=on?'0':'1';b.textContent=on?'🌐 Tradução: OFF':'🌐 Tradução: ON';if(on)$('liveTranslation').textContent=''};$('liveToggleAutoSpeak').dataset.on='1';$('liveToggleAutoSpeak').onclick=()=>{const b=$('liveToggleAutoSpeak'),on=b.dataset.on!=='0';b.dataset.on=on?'0':'1';b.textContent=on?'🔊 Voz automática: OFF':'🔊 Voz automática: ON'}}
function install(){styles();view();nav();updateHelp();try{const old=JSON.parse(localStorage.getItem(LIVE)||'{}');if(Array.isArray(old.history))history=old.history.slice(-8)}catch{}renderHistory();document.addEventListener('click',e=>{if(e.target.closest('.nav-button,.translation-nav')&&!e.target.closest('#graceLiveNav'))$('graceLiveNav')?.classList.remove('active')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();