(()=>{'use strict';
const $=id=>document.getElementById(id), COURSE='englishos-grace-v7', KEY='englishos-guided-path-v1';
const M=(start,end,phase,level,title,goal,grammar,scenario,phrases)=>({start,end,phase,level,title,goal,grammar,scenario,phrases});
const modules=[
M(1,5,'Fundação','A1','Primeiro contato','Cumprimentar e se apresentar sem decorar um discurso longo.','I am / My name is','daily',[
['Hello. My name is Gustavo.','Olá. Meu nome é Gustavo.','Say your name.','Comece somente com nome e saudação.'],
['I am a project manager.','Eu sou gerente de projetos.','Say what you do.','Use “I am” + função.'],
['I work with technology.','Eu trabalho com tecnologia.','Say your area.','Uma frase curta já é suficiente.'],
['I have over seventeen years of experience.','Eu tenho mais de dezessete anos de experiência.','Say how much experience you have.','Use “I have” para experiência.']]),
M(6,10,'Fundação','A1','Nome, números e agenda','Soletrar, dizer horários, datas e números básicos.','It is / at / on','daily',[
['My last name is Marques.','Meu sobrenome é Marques.','Say your last name.','Fale devagar e com clareza.'],
['The meeting is at three o’clock.','A reunião é às três horas.','Say the meeting time.','Use “at” antes do horário.'],
['The meeting is on Monday.','A reunião é na segunda-feira.','Say the meeting day.','Use “on” antes do dia.'],
['The project is eighty percent complete.','O projeto está oitenta por cento concluído.','Say a simple percentage.','Treine números dentro de uma frase útil.']]),
M(11,15,'Fundação','A1','Minha rotina de trabalho','Explicar atividades comuns do dia sem usar tempos complexos.','I + verbo no presente','daily',[
['I review priorities every morning.','Eu reviso as prioridades todas as manhãs.','Say one morning activity.','Presente simples para rotina.'],
['I lead project meetings.','Eu conduzo reuniões de projeto.','Say one responsibility.','Use verbo direto: I lead.'],
['I support the team.','Eu apoio a equipe.','Say how you help the team.','Frase curta e natural.'],
['I check risks and deadlines.','Eu verifico riscos e prazos.','Say what you check.','Junte só dois itens por vez.']]),
M(16,20,'Fundação','A1','Perguntar e pedir ajuda','Fazer perguntas essenciais e sobreviver quando não entender.','What / When / Could you...?','daily',[
['What is the objective?','Qual é o objetivo?','Ask about the objective.','Uma pergunta por vez.'],
['When is the deadline?','Quando é o prazo?','Ask about the deadline.','Use “When is...?”'],
['Could you repeat that, please?','Você poderia repetir, por favor?','Ask someone to repeat.','Frase de sobrevivência essencial.'],
['Could you speak more slowly, please?','Você poderia falar mais devagar, por favor?','Ask someone to slow down.','Use quando a fala estiver rápida demais.']]),
M(21,25,'Fundação','A1','Small talk simples','Falar um pouco de vida pessoal antes de entrar no trabalho.','I live / I like / I have','daily',[
['I live in Brasília.','Eu moro em Brasília.','Say where you live.','Use “I live in”.'],
['I live with my family.','Eu moro com minha família.','Say who you live with.','Não precisa detalhar demais.'],
['I like walking and studying.','Eu gosto de caminhar e estudar.','Say two things you like.','Use “I like” + atividade.'],
['I study theology in my free time.','Eu estudo teologia no meu tempo livre.','Say one personal interest.','Uma informação pessoal curta.']]),
M(26,30,'Fundação','A1','Revisão 1 — fale sem roteiro','Juntar o que já foi aprendido em respostas curtas.','Revisão','daily',[
['Hello. I am Gustavo, and I work with technology.','Olá. Eu sou Gustavo e trabalho com tecnologia.','Introduce yourself in two short ideas.','Não tente falar tudo de uma vez.'],
['I lead meetings and support the team.','Eu conduzo reuniões e apoio a equipe.','Describe two responsibilities.','Use apenas estruturas já estudadas.'],
['The meeting is on Monday at three o’clock.','A reunião é na segunda-feira às três horas.','Say a day and time.','Junte dia + horário.'],
['Could you repeat that more slowly, please?','Você poderia repetir isso mais devagar, por favor?','Ask for help politely.','Frase de segurança para conversas reais.']]),
M(31,35,'Comunicação','A1–A2','Abrindo uma reunião','Cumprimentar, dizer objetivo e começar uma pauta.','Let us / Today we will','meeting',[
['Good morning, everyone.','Bom dia a todos.','Open the meeting.','Comece com uma saudação simples.'],
['Today we will review the project status.','Hoje vamos revisar o status do projeto.','Say the meeting objective.','Uma frase de objetivo.'],
['Let us start with the main priorities.','Vamos começar pelas principais prioridades.','Start the agenda.','Use “Let us” para conduzir.'],
['We have three items on the agenda.','Temos três itens na pauta.','Say how many agenda items there are.','Use números já conhecidos.']]),
M(36,40,'Comunicação','A1–A2','Status do projeto','Dizer o que está bem, o que falta e o próximo passo.','The project is / We have / We need','meeting',[
['The project is on track.','O projeto está no prazo.','Give a positive status.','Frase executiva curta.'],
['We completed the first milestone.','Concluímos o primeiro marco.','Say what was completed.','Primeiro contato com passado útil.'],
['We still need approval.','Ainda precisamos de aprovação.','Say what is missing.','Use “We need”.'],
['The next step is testing.','O próximo passo é o teste.','Say the next step.','Estrutura fixa muito útil.']]),
M(41,45,'Comunicação','A1–A2','Pedidos profissionais','Pedir documentos, respostas e ações com educação.','Could you / Please','client',[
['Could you share the document, please?','Você poderia compartilhar o documento, por favor?','Ask for a document.','Pedido educado com “Could you”.'],
['Could you confirm the date, please?','Você poderia confirmar a data, por favor?','Ask for confirmation.','Troque só o objeto do pedido.'],
['Please send the latest version.','Por favor, envie a versão mais recente.','Ask for the latest version.','Pedido direto, mas educado.'],
['Could you reply by tomorrow?','Você poderia responder até amanhã?','Ask for a deadline.','Adicione prazo ao pedido.']]),
M(46,50,'Comunicação','A1–A2','Riscos e impedimentos','Explicar um problema sem culpar pessoas.','We have / We are blocked by / This may','meeting',[
['We have one important risk.','Temos um risco importante.','Introduce a risk.','Comece simples antes de explicar.'],
['We are blocked by a missing approval.','Estamos bloqueados pela falta de uma aprovação.','Explain the blocker.','Foque na dependência, não em culpados.'],
['This may affect the deadline.','Isso pode afetar o prazo.','Explain an impact.','Use “may” para possibilidade.'],
['We need a decision today.','Precisamos de uma decisão hoje.','State what is needed.','Feche com ação necessária.']]),
M(51,55,'Comunicação','A2','Prazos e estimativas','Dizer quando algo pode ser entregue e negociar escopo.','We can / It will take','client',[
['We can deliver the first version on Friday.','Podemos entregar a primeira versão na sexta-feira.','Give a delivery date.','Use “We can deliver”.'],
['It will take two more days.','Vai levar mais dois dias.','Give a simple estimate.','Use “It will take”.'],
['The complete scope needs more time.','O escopo completo precisa de mais tempo.','Explain a limitation.','Separe versão inicial e escopo completo.'],
['We can review the date together.','Podemos revisar a data juntos.','Invite negotiation.','Tom colaborativo.']]),
M(56,60,'Comunicação','A2','Fechamento e follow-up','Encerrar reunião, confirmar ações e mandar acompanhamento.','I will / We agreed / Please','meeting',[
['We agreed on the next steps.','Nós concordamos com os próximos passos.','Confirm an agreement.','Resumo curto.'],
['I will send the notes today.','Eu enviarei as notas hoje.','State your action.','Use “I will”.'],
['Please confirm your action item.','Por favor, confirme sua ação.','Ask for confirmation.','Ação clara e objetiva.'],
['Thank you. I will follow up tomorrow.','Obrigado. Vou acompanhar amanhã.','Close professionally.','Fechamento simples.']]),
M(61,70,'Autonomia','A2','Resultados e passado recente','Explicar o que aconteceu e o resultado.','Past Simple / Present Perfect básico','meeting',[
['We completed the migration last week.','Concluímos a migração na semana passada.','Report a completed action.','Use passado com tempo definido.'],
['The team solved the issue.','A equipe resolveu o problema.','Report a solved problem.','Verbo no passado em contexto real.'],
['We have improved the process.','Nós melhoramos o processo.','Describe a recent improvement.','Resultado relevante até agora.'],
['The change reduced the response time.','A mudança reduziu o tempo de resposta.','Describe an impact.','Conecte ação e resultado.']]),
M(71,80,'Autonomia','A2–B1','Opiniões e decisões','Dar opinião, concordar e propor uma decisão.','I think / I agree / I suggest','meeting',[
['I think this option is safer.','Eu acho que esta opção é mais segura.','Give an opinion.','Comece com “I think”.'],
['I agree with the proposed approach.','Eu concordo com a abordagem proposta.','Agree professionally.','Concordância objetiva.'],
['I suggest a smaller first release.','Eu sugiro uma primeira entrega menor.','Make a suggestion.','Use “I suggest”.'],
['We need to decide today.','Precisamos decidir hoje.','Call for a decision.','Seja claro sobre a necessidade.']]),
M(81,90,'Autonomia','A2–B1','Problema → solução','Explicar causa, opção e recomendação.','because / so / therefore','meeting',[
['The issue happened because the access was missing.','O problema aconteceu porque o acesso estava faltando.','Explain a cause.','Use “because”.'],
['We created a temporary solution.','Criamos uma solução temporária.','Describe the response.','Passado simples.'],
['So the team can continue working.','Assim a equipe pode continuar trabalhando.','Explain the benefit.','Conecte causa e efeito.'],
['I recommend fixing the root cause next.','Recomendo corrigir a causa raiz em seguida.','Give a recommendation.','Feche com recomendação.']]),
M(91,100,'Carreira','B1','Entrevista — apresentação','Contar trajetória profissional de forma clara e curta.','Present Perfect / Past Simple','interview',[
['I have worked in technology for over seventeen years.','Eu trabalho com tecnologia há mais de dezessete anos.','Summarize your experience.','Use “have worked” para trajetória.'],
['I started my career in technology operations.','Comecei minha carreira em operações de tecnologia.','Say how your career began.','Conte um ponto por vez.'],
['I moved into project and agile leadership.','Migrei para liderança de projetos e ágil.','Explain your evolution.','Mostre progressão de carreira.'],
['Today I lead complex technology initiatives.','Hoje lidero iniciativas complexas de tecnologia.','Describe your current profile.','Feche no presente.']]),
M(101,110,'Carreira','B1','Liderança e feedback','Falar sobre equipe, conflitos, desenvolvimento e resultados.','I help / I expect / I learned','interview',[
['I help teams remove blockers and make decisions.','Ajudo equipes a remover impedimentos e tomar decisões.','Describe your leadership style.','Use ação + resultado.'],
['I give clear and respectful feedback.','Dou feedback claro e respeitoso.','Describe feedback.','Frase direta.'],
['I expect ownership and transparency.','Espero responsabilidade e transparência.','State an expectation.','Vocabulário de liderança.'],
['I learned to adapt my leadership style.','Aprendi a adaptar meu estilo de liderança.','Share a lesson learned.','Mostre reflexão.']]),
M(111,120,'Carreira','B1','Negociação e networking','Criar conexão e negociar prioridades sem confronto.','Would / Could / What if','client',[
['I would like to understand your priority.','Gostaria de entender sua prioridade.','Open a negotiation.','Pergunte antes de defender posição.'],
['Could we review the scope together?','Poderíamos revisar o escopo juntos?','Invite collaboration.','Tom colaborativo.'],
['What if we deliver in two phases?','E se entregarmos em duas fases?','Offer an alternative.','Use “What if”.'],
['That option works for both sides.','Essa opção funciona para os dois lados.','Confirm alignment.','Feche no ganho mútuo.']]),
M(121,130,'Especialização','B1','Arquitetura e AWS','Explicar arquitetura sem entrar em detalhes desnecessários.','It connects / It uses / The purpose is','technology',[
['The solution connects cloud and on-premises systems.','A solução conecta sistemas em nuvem e on-premises.','Describe the architecture at a high level.','Comece pela visão geral.'],
['It uses AWS services for scalability.','Ela usa serviços AWS para escalabilidade.','Explain one technology choice.','Uma justificativa por vez.'],
['The purpose is to improve reliability.','O objetivo é melhorar a confiabilidade.','Explain the purpose.','Tecnologia ligada ao benefício.'],
['This component handles authentication.','Este componente cuida da autenticação.','Explain one component.','Frase de arquitetura simples.']]),
M(131,140,'Especialização','B1–B2','Segurança, dados e IA','Explicar conceitos técnicos em linguagem de negócio.','must / should / can','technology',[
['Access must follow the security policy.','O acesso deve seguir a política de segurança.','State a security requirement.','Use “must” para obrigação.'],
['Data should be validated before processing.','Os dados devem ser validados antes do processamento.','State a recommendation.','Use “should” para recomendação.'],
['AI can support faster analysis.','A IA pode apoiar análises mais rápidas.','Explain an AI benefit.','Evite promessas absolutas.'],
['We need traceability for every decision.','Precisamos de rastreabilidade para cada decisão.','State a governance need.','Conecte técnica e controle.']]),
M(141,150,'Especialização','B1–B2','Governança e comunicação executiva','Resumir situação, impacto e decisão necessária.','The key point is / The impact is / We recommend','meeting',[
['The key point is the dependency on approval.','O ponto principal é a dependência de aprovação.','State the key point.','Uma mensagem principal.'],
['The impact is a possible delay.','O impacto é um possível atraso.','State the impact.','Evite excesso de contexto.'],
['We recommend approving option two.','Recomendamos aprovar a opção dois.','Give a recommendation.','Recomendação clara.'],
['The decision is needed by Friday.','A decisão é necessária até sexta-feira.','State the decision deadline.','Feche com prazo.']]),
M(151,160,'Imersão','B2','Cliente e apresentação','Apresentar valor, progresso e próximos passos com segurança.','Signposting / transitions','client',[
['First, I will summarize the current situation.','Primeiro, vou resumir a situação atual.','Open a presentation.','Use sinalização para guiar o ouvinte.'],
['The main benefit is faster decision-making.','O principal benefício é uma tomada de decisão mais rápida.','Present a benefit.','Fale de valor antes de detalhe.'],
['Now let us look at the main risk.','Agora vamos olhar o principal risco.','Move to the next point.','Use transição explícita.'],
['Finally, these are the next steps.','Por fim, estes são os próximos passos.','Close the presentation.','Fechamento organizado.']]),
M(161,170,'Imersão','B2','Perguntas difíceis e pressão','Responder sem perder clareza quando surgir objeção ou surpresa.','I understand / Based on / Let me clarify','client',[
['I understand your concern.','Eu entendo sua preocupação.','Acknowledge a concern.','Reconheça antes de responder.'],
['Based on the current data, the date is realistic.','Com base nos dados atuais, a data é realista.','Answer with evidence.','Evite responder só com opinião.'],
['Let me clarify one important point.','Deixe-me esclarecer um ponto importante.','Correct a misunderstanding.','Use “Let me clarify”.'],
['I do not have that information yet, but I will confirm it.','Ainda não tenho essa informação, mas vou confirmá-la.','Handle an unknown answer.','Não invente resposta.']]),
M(171,180,'Imersão','B2','Integração e fluência funcional','Usar o que aprendeu em situações completas, sem decorar.','Integração','meeting',[
['Let me give you a concise status update.','Deixe-me dar uma atualização de status concisa.','Open a full status update.','Organize antes de falar.'],
['We made progress, but one risk still needs attention.','Avançamos, mas um risco ainda precisa de atenção.','Balance progress and risk.','Contraste duas ideias.'],
['My recommendation is to proceed in two phases.','Minha recomendação é prosseguir em duas fases.','Give a recommendation.','Posicione-se com clareza.'],
['I am ready to answer your questions.','Estou pronto para responder às suas perguntas.','Close confidently.','Feche e abra espaço para perguntas.']])
];
const steps=[['understand','1','Entenda'],['listen','2','Ouça'],['repeat','3','Repita'],['build','4','Construa'],['speak','5','Fale']];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function course(){try{return JSON.parse(localStorage.getItem(COURSE)||'{}')}catch{return{}}}
function day(){const g=load();return Math.max(1,Math.min(180,Number(g.currentDay||course().day||1)))}
function moduleFor(d=day()){return modules.find(m=>d>=m.start&&d<=m.end)||modules[0]}
function phraseFor(d=day()){const m=moduleFor(d),off=d-m.start,idx=off%m.phrases.length,round=Math.floor(off/m.phrases.length);return {m,p:m.phrases[idx],round,index:idx}}
function stateForDay(d=day()){const s=load();s.steps=s.steps||{};s.steps[d]=s.steps[d]||{step:0,done:[],attempts:{}};return {s,daily:s.steps[d]}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function styles(){if($('guidedStyles'))return;const s=document.createElement('style');s.id='guidedStyles';s.textContent=`
.guided-nav{border:0;background:linear-gradient(135deg,color-mix(in srgb,var(--brand) 11%,transparent),color-mix(in srgb,var(--brand-2) 8%,transparent));color:var(--text);display:flex;align-items:center;gap:10px;padding:11px 12px;border-radius:12px;width:100%;font:inherit;cursor:pointer}.guided-nav:hover,.guided-nav.active{background:var(--brand-soft)}
.guided-hero{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr);gap:16px;align-items:start}.guided-stage{overflow:hidden;padding:0!important}.guided-stage-head{padding:20px 22px;border-bottom:1px solid var(--line);background:linear-gradient(135deg,color-mix(in srgb,var(--brand-soft) 75%,var(--panel)),var(--panel));display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.guided-stage-head h3{margin:5px 0 4px;font-size:1.4rem}.guided-stage-head p{margin:0;color:var(--muted)}.guided-module-chip{padding:7px 10px;border-radius:999px;background:var(--brand);color:#fff;font-weight:900;font-size:.78rem;white-space:nowrap}
.guided-steps{display:grid;grid-template-columns:repeat(5,1fr);gap:0;border-bottom:1px solid var(--line)}.guided-step{padding:12px 8px;text-align:center;color:var(--muted);font-size:.78rem;font-weight:850;background:var(--panel)}.guided-step b{display:grid;place-items:center;width:25px;height:25px;margin:0 auto 5px;border-radius:50%;background:var(--panel-2);border:1px solid var(--line)}.guided-step.active{color:var(--brand);background:var(--brand-soft)}.guided-step.active b,.guided-step.done b{background:var(--brand);color:#fff;border-color:var(--brand)}
.guided-body{min-height:410px;padding:28px 24px;display:flex;flex-direction:column;justify-content:center}.guided-kicker{font-size:.75rem;letter-spacing:.1em;font-weight:900;color:var(--brand);text-transform:uppercase}.guided-big{font-size:clamp(1.65rem,4vw,2.35rem);line-height:1.25;margin:10px 0}.guided-pt{font-size:1.05rem;color:var(--muted);margin:0 0 18px}.guided-note{padding:13px 15px;border-radius:13px;background:var(--panel-2);color:var(--muted);line-height:1.55}.guided-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:20px}.guided-actions button{min-height:45px}.guided-result{margin-top:16px;padding:14px 15px;border-left:4px solid var(--brand-2);border-radius:11px;background:var(--panel-2);line-height:1.55}.guided-input{margin-top:14px}.guided-input textarea{min-height:90px}
.guided-side{display:grid;gap:16px}.guided-progress-card h3{margin:5px 0}.guided-progress-line{height:10px;background:var(--panel-2);border-radius:999px;overflow:hidden;margin:13px 0}.guided-progress-line i{display:block;height:100%;background:linear-gradient(90deg,var(--brand),var(--brand-2))}.guided-modules{display:grid;gap:7px;max-height:430px;overflow:auto}.guided-module-row{display:grid;grid-template-columns:35px 1fr auto;gap:9px;align-items:center;padding:10px;border-radius:12px;background:var(--panel-2);border:1px solid transparent}.guided-module-row.current{background:var(--brand-soft);border-color:color-mix(in srgb,var(--brand) 35%,var(--line))}.guided-module-row.locked{opacity:.55}.guided-module-row .num{width:32px;height:32px;border-radius:10px;display:grid;place-items:center;background:var(--panel);font-weight:900}.guided-module-row small{display:block;color:var(--muted);margin-top:2px}.guided-dashboard{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:17px 18px;margin:0 0 16px;border-radius:18px;border:1px solid var(--line);background:linear-gradient(135deg,var(--panel),color-mix(in srgb,var(--brand-soft) 60%,var(--panel)));box-shadow:var(--shadow)}.guided-dashboard b{display:block;font-size:1.05rem}.guided-dashboard small{color:var(--muted);line-height:1.45}.guided-mic.is-recording{background:#d9364f!important;color:#fff!important;animation:pulse .7s infinite alternate}
@media(max-width:950px){.guided-hero{grid-template-columns:1fr}.guided-steps{grid-template-columns:repeat(5,1fr)}}@media(max-width:620px){.guided-stage-head,.guided-dashboard{flex-direction:column}.guided-dashboard button{width:100%}.guided-step{font-size:.68rem;padding:10px 3px}.guided-body{padding:22px 17px}}`;
document.head.appendChild(s)}
function nav(){if($('guidedPathNav'))return;const n=document.querySelector('.nav');if(!n)return;const b=document.createElement('button');b.id='guidedPathNav';b.className='guided-nav';b.type='button';b.innerHTML='<span>🧭</span><b>Trilha guiada</b>';const first=n.querySelector('.nav-button');first?.insertAdjacentElement('afterend',b);if(!first)n.prepend(b);b.onclick=open}
function createView(){if($('guidedPath'))return;const main=document.querySelector('.main-content');if(!main)return;const sec=document.createElement('section');sec.id='guidedPath';sec.className='view';sec.innerHTML='<div id="guidedContent"></div>';main.insertBefore(sec,$('teacher')||main.firstChild)}
function dashboard(){if($('guidedDashboard'))return;const d=$('dashboard'),metrics=d?.querySelector('.metrics-grid');if(!d||!metrics)return;const x=document.createElement('div');x.id='guidedDashboard';x.className='guided-dashboard';x.innerHTML='<div><b id="guidedDashTitle"></b><small id="guidedDashText"></small></div><button class="primary" id="guidedDashOpen">Continuar módulo</button>';metrics.insertAdjacentElement('afterend',x);$('guidedDashOpen').onclick=open}
function open(){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='guidedPath'));document.querySelectorAll('.nav-button,.translation-nav,.grace-live-nav,.guided-nav').forEach(b=>b.classList.remove('active'));$('guidedPathNav')?.classList.add('active');if($('todayLabel'))$('todayLabel').textContent='TRILHA GUIADA';if($('pageTitle'))$('pageTitle').textContent='Aprenda em pequenas etapas';if($('pageSubtitle'))$('pageSubtitle').textContent='Uma estrutura por vez. Ouça, repita, construa e só depois converse.';render();window.scrollTo({top:0,behavior:'smooth'})}
function updateDashboard(){const d=day(),{m}=phraseFor(d);if($('guidedDashTitle'))$('guidedDashTitle').textContent=`Dia ${d} • ${m.title}`;if($('guidedDashText'))$('guidedDashText').textContent=`Módulo ${modules.indexOf(m)+1} de ${modules.length}. ${m.goal}`}
function modulesHtml(d){const current=moduleFor(d),idx=modules.indexOf(current);return modules.map((m,i)=>`<div class="guided-module-row ${m===current?'current':''} ${i>idx?'locked':''}"><span class="num">${i+1}</span><div><b>${esc(m.title)}</b><small>${m.level} • dias ${m.start}–${m.end}</small></div><span>${i<idx?'✓':m===current?'Agora':'🔒'}</span></div>`).join('')}
function stepTabs(daily){return steps.map((x,i)=>`<div class="guided-step ${i===daily.step?'active':''} ${daily.done.includes(i)?'done':''}"><b>${daily.done.includes(i)?'✓':x[1]}</b>${x[2]}</div>`).join('')}
async function tts(text,slow=false){try{const r=await fetch('/api/tts',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:'hannah'})});if(!r.ok)throw Error();const blob=await r.blob(),url=URL.createObjectURL(blob),a=new Audio(url);a.playbackRate=slow?.82:1;a.onended=()=>URL.revokeObjectURL(url);await a.play()}catch{if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=slow?.72:.9;speechSynthesis.speak(u)}}}
function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=reject;r.readAsDataURL(blob)})}
async function record(maxMs=7500){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Use Chrome ou Edge e permita o microfone.');const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[];const rec=new MediaRecorder(stream);return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(rec.state==='recording')rec.stop()},maxMs);rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onerror=()=>{clearTimeout(timer);stream.getTracks().forEach(t=>t.stop());reject(Error('Não consegui gravar o áudio.'))};rec.onstop=async()=>{clearTimeout(timer);stream.getTracks().forEach(t=>t.stop());try{const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});resolve({audioBase64:await blobToBase64(blob),mimeType:blob.type})}catch(e){reject(e)}};rec.start()})}
async function transcribe(){const a=await record();const r=await fetch('/api/stt',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(a)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Não consegui entender sua fala.');return d.text||''}
async function ask(stage,payload){if(!window.GraceAI?.ask)throw Error('A Grace ainda está carregando.');const ctx=getContext();return await window.GraceAI.ask('guided_lesson',{stage,day:ctx.day,module:ctx.module,goal:ctx.goal,grammar:ctx.grammar,target:ctx.target,translation:ctx.translation,cue:ctx.cue,help:ctx.help,...payload})}
function markStep(i){const {s,daily}=stateForDay();if(!daily.done.includes(i))daily.done.push(i);daily.step=Math.min(4,i+1);save(s);render()}
function setAttempt(key,value){const {s,daily}=stateForDay();daily.attempts[key]=value;save(s)}
function finishDay(){const d=day(),g=load();g.completedDays=Array.isArray(g.completedDays)?g.completedDays:[];if(!g.completedDays.includes(d))g.completedDays.push(d);g.currentDay=Math.min(180,d+1);g.steps=g.steps||{};save(g);const c=course();c.completed=Array.isArray(c.completed)?c.completed:[];if(!c.completed.includes(d))c.completed.push(d);c.day=Math.min(180,d+1);c.xp=Number(c.xp||0)+35;localStorage.setItem(COURSE,JSON.stringify(c));updateDashboard();render();const box=$('guidedResult');if(box)box.innerHTML='<b>Dia concluído.</b><br>Você avançou uma pequena etapa. O próximo conteúdo só aumenta um pouco a dificuldade.'}
function render(){const d=day(),{m,p,round}=phraseFor(d),{daily}=stateForDay(),mi=modules.indexOf(m),pct=Math.round((d-1)/180*100);updateDashboard();const root=$('guidedContent');if(!root)return;root.innerHTML=`<div class="section-heading"><div><div class="eyebrow">CURSO GUIADO • 180 DIAS</div><h2>${esc(m.title)}</h2><p>${esc(m.goal)}</p></div><span class="status-pill">Dia ${d} de 180</span></div><div class="guided-hero"><article class="card guided-stage"><div class="guided-stage-head"><div><span class="guided-kicker">Módulo ${mi+1} • ${m.phase} • ${m.level}</span><h3>${round?'Revisão e variação':'Microaula do dia'}</h3><p>${esc(m.grammar)}</p></div><span class="guided-module-chip">${steps[daily.step][2]}</span></div><div class="guided-steps">${stepTabs(daily)}</div><div class="guided-body" id="guidedBody"></div></article><aside class="guided-side"><article class="card guided-progress-card"><div class="eyebrow">SEU CAMINHO</div><h3>${pct}% da jornada</h3><div class="guided-progress-line"><i style="width:${pct}%"></i></div><p>Não há pressa. O objetivo é conseguir usar cada estrutura antes de aumentar a dificuldade.</p></article><article class="card"><div class="eyebrow">MÓDULOS</div><div class="guided-modules">${modulesHtml(d)}</div></article></aside></div>`;renderStep(daily.step,m,p,round)}
function renderStep(i,m,p,round){const b=$('guidedBody');if(!b)return;const [en,pt,cue,note]=p,attempt=stateForDay().daily.attempts;const nextLabel=i===4?'Concluir o dia':'Próxima etapa';if(i===0)b.innerHTML=`<div class="guided-kicker">ENTENDA PRIMEIRO</div><div class="guided-big">${esc(en)}</div><p class="guided-pt">${esc(pt)}</p><div class="guided-note"><b>Um ponto apenas:</b> ${esc(note)}${round?' Hoje você está revisando esta estrutura em vez de receber matéria nova.':''}</div><div class="guided-actions"><button class="primary" id="guidedNext">Entendi • continuar</button></div>`;
if(i===1)b.innerHTML=`<div class="guided-kicker">OUÇA SEM PRESSA</div><div class="guided-big">${esc(en)}</div><p class="guided-pt">Primeiro ouça normalmente. Depois ouça devagar.</p><div class="guided-actions"><button class="primary" id="guidedListen">🔊 Ouvir</button><button class="secondary" id="guidedListenSlow">🐢 Ouvir devagar</button><button class="ghost" id="guidedNext">${nextLabel}</button></div>`;
if(i===2)b.innerHTML=`<div class="guided-kicker">REPITA</div><div class="guided-big">${esc(en)}</div><p class="guided-pt">Fale a frase. A Grace vai priorizar se ela foi compreensível — não perfeição.</p><div class="guided-actions"><button class="primary guided-mic" id="guidedRecord">🎙️ Falar agora</button>${attempt.repeat?`<button class="ghost" id="guidedNext">${nextLabel}</button>`:''}</div><div id="guidedResult" class="guided-result ${attempt.repeat?'':'hidden'}">${attempt.repeat?esc(attempt.repeat):''}</div>`;
if(i===3)b.innerHTML=`<div class="guided-kicker">CONSTRUA</div><p class="guided-pt">${esc(cue)}</p><div class="guided-input"><textarea id="guidedAnswer" placeholder="Escreva uma frase curta em inglês..."></textarea></div><div class="guided-actions"><button class="primary" id="guidedCheck">Verificar com a Grace</button>${attempt.build?`<button class="ghost" id="guidedNext">${nextLabel}</button>`:''}</div><div id="guidedResult" class="guided-result ${attempt.build?'':'hidden'}">${attempt.build?esc(attempt.build):''}</div>`;
if(i===4)b.innerHTML=`<div class="guided-kicker">FALE EM CONTEXTO</div><div class="guided-big" style="font-size:1.55rem">${esc(cue)}</div><p class="guided-pt">Responda com uma frase curta. Você pode falar ou digitar. Não precisa inventar vocabulário novo.</p><div class="guided-input"><textarea id="guidedAnswer" placeholder="Sua resposta em inglês..."></textarea></div><div class="guided-actions"><button class="primary guided-mic" id="guidedSpeak">🎙️ Responder falando</button><button class="secondary" id="guidedCheck">Enviar texto</button>${attempt.speak?`<button class="primary" id="guidedFinish">Concluir dia</button>`:''}</div><div id="guidedResult" class="guided-result ${attempt.speak?'':'hidden'}">${attempt.speak?attempt.speak:''}</div>`;
bindStep(i,m,p)}
function resultText(ai){const parts=[];if(ai?.feedback)parts.push(ai.feedback);if(ai?.correction)parts.push(`Correção: ${ai.correction}`);if(ai?.explanation)parts.push(ai.explanation);if(ai?.reply)parts.push(`Grace: ${ai.reply}`);if(ai?.translation)parts.push(`Tradução: ${ai.translation}`);if(ai?.score!=null)parts.push(`Pontuação: ${ai.score}/100`);return parts.join('\n')||'Prática registrada.'}
function bindStep(i,m,p){const [en]=p;$('guidedNext')&&($('guidedNext').onclick=()=>markStep(i));$('guidedListen')&&($('guidedListen').onclick=()=>tts(en,false));$('guidedListenSlow')&&($('guidedListenSlow').onclick=()=>tts(en,true));
if($('guidedRecord'))$('guidedRecord').onclick=async e=>{const btn=e.currentTarget,out=$('guidedResult');btn.disabled=true;btn.classList.add('is-recording');btn.textContent='🎙️ Ouvindo...';out.classList.remove('hidden');out.textContent='Fale a frase uma vez. A gravação encerra sozinha.';try{const tr=await transcribe();const ai=await ask('repeat',{transcript:tr});const txt=`Você falou: ${tr}\n${resultText(ai)}`;setAttempt('repeat',txt);out.textContent=txt;markStep(2)}catch(err){out.textContent=err.message||'Não consegui avaliar agora.'}finally{btn.disabled=false;btn.classList.remove('is-recording');btn.textContent='🎙️ Falar novamente'}};
if($('guidedCheck'))$('guidedCheck').onclick=async e=>{const ans=$('guidedAnswer')?.value.trim();if(!ans)return;const btn=e.currentTarget,out=$('guidedResult');btn.disabled=true;out.classList.remove('hidden');out.textContent='Grace está olhando somente para o conteúdo deste módulo...';try{const ai=await ask(i===4?'speak':'build',{answer:ans});const txt=resultText(ai);setAttempt(i===4?'speak':'build',txt);out.innerHTML=esc(txt).replace(/\n/g,'<br>');if(i===3)markStep(3);else render()}catch(err){out.textContent=err.message||'Não consegui avaliar agora.'}finally{btn.disabled=false}};
if($('guidedSpeak'))$('guidedSpeak').onclick=async e=>{const btn=e.currentTarget,out=$('guidedResult');btn.disabled=true;btn.classList.add('is-recording');btn.textContent='🎙️ Ouvindo...';out.classList.remove('hidden');out.textContent='Responda com uma frase curta.';try{const tr=await transcribe();if($('guidedAnswer'))$('guidedAnswer').value=tr;const ai=await ask('speak',{answer:tr});const txt=`Você falou: ${tr}\n${resultText(ai)}`;setAttempt('speak',txt);out.innerHTML=esc(txt).replace(/\n/g,'<br>');render()}catch(err){out.textContent=err.message||'Não consegui avaliar agora.'}finally{btn.disabled=false;btn.classList.remove('is-recording');btn.textContent='🎙️ Responder falando'}};
$('guidedFinish')&&($('guidedFinish').onclick=finishDay)}
function getContext(){const d=day(),{m,p,round}=phraseFor(d);return {day:d,module:m.title,moduleIndex:modules.indexOf(m)+1,phase:m.phase,level:m.level,goal:m.goal,grammar:m.grammar,scenario:m.scenario,target:p[0],translation:p[1],cue:p[2],note:p[3],review:Boolean(round),help:d<=30?'high':d<=60?'medium':'low'}}
function init(){styles();createView();nav();dashboard();updateDashboard();document.addEventListener('click',e=>{if(e.target.closest('.nav-button,.translation-nav,.grace-live-nav'))$('guidedPathNav')?.classList.remove('active')});window.EnglishOSGuided={open,getContext,currentDay:day,modules}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();