(()=>{'use strict';
const $=id=>document.getElementById(id);
let signature='';
function css(){if($('mobileV22Css'))return;const s=document.createElement('style');s.id='mobileV22Css';s.textContent=`
@media(max-width:820px){
html,body{max-width:100%;overflow-x:hidden}body{overscroll-behavior-x:none}.app-shell{display:block!important;min-width:0!important}.main-content{width:100%!important;max-width:100vw!important;padding:12px 10px calc(82px + env(safe-area-inset-bottom))!important;overflow-x:hidden}.topbar{padding:0!important}.topbar h1{font-size:1.45rem!important}.top-actions{gap:6px!important;flex-wrap:wrap}.top-actions .soft-button{padding:7px 9px!important;font-size:.76rem!important}
.sidebar{left:0!important;right:0!important;bottom:0!important;top:auto!important;width:100%!important;height:calc(68px + env(safe-area-inset-bottom))!important;padding:6px 7px calc(6px + env(safe-area-inset-bottom))!important;border:0!important;border-top:1px solid color-mix(in srgb,var(--line) 80%,transparent)!important;background:color-mix(in srgb,var(--panel) 91%,transparent)!important;backdrop-filter:blur(22px) saturate(1.25)!important;-webkit-backdrop-filter:blur(22px) saturate(1.25)!important;box-shadow:0 -12px 36px rgba(21,45,70,.12)!important;z-index:1900!important;overflow:visible!important}.brand,.sidebar-card{display:none!important}.nav{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:3px!important;overflow:visible!important;height:100%!important}.nav>*{display:none!important}.nav>.mobile-primary,.nav>#mobileMoreNav{display:flex!important;min-width:0!important;height:55px!important;padding:4px 2px!important;border-radius:13px!important;align-items:center!important;justify-content:center!important;flex-direction:column!important;gap:2px!important;background:transparent!important;color:var(--muted)!important;font-size:.62rem!important;line-height:1.05!important;text-align:center!important;border:0!important}.nav>.mobile-primary span,.nav>#mobileMoreNav span{font-size:1.1rem!important;line-height:1!important;width:auto!important}.nav>.mobile-primary b,.nav>#mobileMoreNav b{font-size:.62rem!important;max-width:70px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.nav>.mobile-primary.active{background:var(--brand-soft)!important;color:var(--brand)!important}.nav>#graceLiveNav.mobile-primary{font-weight:900!important}.nav>#graceLiveNav.mobile-primary.active{background:linear-gradient(135deg,color-mix(in srgb,var(--brand) 16%,var(--panel)),color-mix(in srgb,var(--brand-2) 14%,var(--panel)))!important}
.mobile-more-sheet{position:fixed;z-index:1880;left:10px;right:10px;bottom:calc(76px + env(safe-area-inset-bottom));max-height:min(62vh,520px);padding:10px;border:1px solid var(--line);border-radius:22px;background:color-mix(in srgb,var(--panel) 96%,transparent);box-shadow:0 24px 70px rgba(20,42,70,.28);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);transform:translateY(18px) scale(.985);opacity:0;pointer-events:none;transition:.2s ease;overflow:auto}.mobile-more-sheet.open{transform:none;opacity:1;pointer-events:auto}.mobile-more-head{display:flex;align-items:center;justify-content:space-between;padding:6px 7px 10px}.mobile-more-head b{font-size:.92rem}.mobile-more-head button{width:34px;height:34px;border:0;border-radius:50%;background:var(--panel-2);color:var(--text);font-size:1rem}.mobile-more-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.mobile-more-item{min-height:70px;border:1px solid var(--line);border-radius:15px;background:var(--panel-2);color:var(--text);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;padding:8px 4px;font:inherit}.mobile-more-item span{font-size:1.25rem}.mobile-more-item b{font-size:.72rem;text-align:center;line-height:1.15}.mobile-more-backdrop{position:fixed;inset:0;z-index:1870;background:rgba(4,13,24,.22);opacity:0;pointer-events:none;transition:.2s}.mobile-more-backdrop.open{opacity:1;pointer-events:auto}
.translation-fab{width:46px!important;height:46px!important;right:12px!important;bottom:calc(82px + env(safe-area-inset-bottom))!important;padding:0!important;font-size:0!important;display:grid!important;place-items:center!important;box-shadow:0 10px 28px rgba(31,87,132,.25)!important;z-index:1750!important}.translation-fab:before{content:'🌐';font-size:20px!important;line-height:1!important}
body.mobile-grace-live .topbar{display:none!important}body.mobile-grace-live .main-content{padding-top:7px!important}body.mobile-grace-live #graceLive>.section-heading{display:none!important}body.mobile-grace-live .translation-fab{display:none!important}
#graceLive{width:100%!important;max-width:100%!important}.live2-layout{grid-template-columns:1fr!important;gap:10px!important}.live2-stage{min-height:0!important;width:100%!important;border-radius:24px!important;overflow:hidden!important}.live2-top{min-height:52px!important;padding:11px 108px 11px 13px!important;display:flex!important;flex-direction:row!important;align-items:center!important;gap:7px!important}.live2-state{font-size:.95rem!important}.live2-badge{display:none!important}.future-mode{top:9px!important;right:9px!important}.future-mode button{font-size:.74rem!important;padding:7px 10px!important}.future-hud{display:flex!important;grid-template-columns:none!important;gap:5px!important;margin:0!important;padding:7px 9px!important;overflow-x:auto!important;overscroll-behavior-x:contain;scrollbar-width:none;border-bottom:1px solid rgba(255,255,255,.055)}.future-hud::-webkit-scrollbar{display:none}.future-hud span{flex:0 0 auto!important;min-width:84px!important;padding:5px 7px!important;border-radius:9px!important;font-size:.49rem!important;letter-spacing:.06em!important}.future-hud b{font-size:.62rem!important;margin-top:1px!important}.live2-presence{min-height:0!important;padding:7px 9px 6px!important}.live2-portrait.grace3d{width:min(78vw,300px)!important;height:min(39vh,325px)!important;aspect-ratio:auto!important;border-radius:25px!important}.grace3d-label{left:9px!important;top:9px!important;padding:5px 7px!important;font-size:.49rem!important}.grace3d-status{right:8px!important;top:9px!important;font-size:.46rem!important;padding:5px 7px!important}.grace3d-credit{display:none!important}.live2-caption{margin:0 9px!important;padding:12px 13px!important;border-radius:15px!important}.live2-caption p{font-size:.96rem!important;line-height:1.42!important;margin-top:5px!important}.live2-caption small{font-size:.8rem!important;line-height:1.35!important}.dialogue-coach{padding:11px 12px!important;margin-top:9px!important}.dialogue-coach .dc-answer{font-size:1rem!important}.dialogue-coach .dc-title,.dialogue-coach .dc-hint{font-size:.78rem!important}.dialogue-coach .dc-note{font-size:.67rem!important}.future-transcript{font-size:.75rem!important;padding:8px 9px!important}.live2-controls{padding:9px 9px 11px!important;gap:7px!important;flex-wrap:nowrap!important;overflow-x:auto!important;justify-content:flex-start!important;scrollbar-width:none}.live2-controls::-webkit-scrollbar{display:none}.live2-controls button{flex:0 0 auto!important;min-height:42px!important;padding:8px 10px!important;font-size:.72rem!important}.live2-mic{width:56px!important;height:56px!important;min-width:56px!important;padding:0!important;font-size:1.25rem!important;order:-1}.live2-side{gap:10px!important;margin-top:0!important}.live2-side>.card{padding:14px!important}.live2-history{max-height:180px!important}
body.grace-immersive #graceLive{padding:6px!important}body.grace-immersive .live2-layout{grid-template-columns:1fr!important}body.grace-immersive .live2-stage{min-height:calc(100dvh - 88px - env(safe-area-inset-bottom))!important}body.grace-immersive .live2-side{display:none!important}body.grace-immersive .live2-portrait.grace3d{height:min(44vh,350px)!important;width:min(82vw,320px)!important}
.card{max-width:100%!important}.section-heading h2{font-size:1.25rem!important}.section-heading p{font-size:.88rem!important}.metrics-grid{gap:7px!important}.metric-card{padding:13px!important}.guided-hero{grid-template-columns:1fr!important}.guided-stage-head{padding:15px!important}.guided-body{min-height:0!important;padding:20px 15px!important}.guided-steps{overflow-x:auto!important}.guided-step{min-width:68px!important}
}
@media(max-width:390px){.live2-portrait.grace3d{width:min(76vw,280px)!important;height:min(37vh,300px)!important}.mobile-more-grid{grid-template-columns:repeat(3,1fr)}.nav>.mobile-primary b,.nav>#mobileMoreNav b{font-size:.58rem!important}.future-hud span{min-width:79px!important}}
`;
document.head.appendChild(s)}
function viewport(){const m=document.querySelector('meta[name="viewport"]');if(m)m.setAttribute('content','width=device-width,initial-scale=1,viewport-fit=cover')}
function sourceIcon(el){return el?.querySelector('span')?.textContent?.trim()||'•'}
function sourceLabel(el){return el?.querySelector('b')?.textContent?.trim()||el?.textContent?.trim()||'Item'}
function navSources(){return [...document.querySelectorAll('.nav > button')].filter(b=>b.id!=='mobileMoreNav')}
function isPrimary(el){return el?.dataset?.view==='dashboard'||el?.dataset?.view==='lesson'||el?.id==='guidedPathNav'||el?.id==='graceLiveNav'}
function ensureMore(){const nav=document.querySelector('.nav');if(!nav)return null;let b=$('mobileMoreNav');if(!b){b=document.createElement('button');b.id='mobileMoreNav';b.type='button';b.innerHTML='<span>•••</span><b>Mais</b>';nav.appendChild(b);b.onclick=()=>toggleSheet()}return b}
function ensureSheet(){let sheet=$('mobileMoreSheet');if(sheet)return sheet;const back=document.createElement('div');back.id='mobileMoreBackdrop';back.className='mobile-more-backdrop';back.onclick=closeSheet;document.body.appendChild(back);sheet=document.createElement('section');sheet.id='mobileMoreSheet';sheet.className='mobile-more-sheet';sheet.innerHTML='<div class="mobile-more-head"><b>Mais recursos</b><button type="button" id="mobileMoreClose">✕</button></div><div class="mobile-more-grid" id="mobileMoreGrid"></div>';document.body.appendChild(sheet);$('mobileMoreClose').onclick=closeSheet;return sheet}
function closeSheet(){ $('mobileMoreSheet')?.classList.remove('open');$('mobileMoreBackdrop')?.classList.remove('open') }
function toggleSheet(){ensureSheet();const open=!$('mobileMoreSheet').classList.contains('open');$('mobileMoreSheet').classList.toggle('open',open);$('mobileMoreBackdrop').classList.toggle('open',open)}
function buildNav(){const nav=document.querySelector('.nav');if(!nav)return;const sources=navSources();sources.forEach(el=>el.classList.toggle('mobile-primary',isPrimary(el)));ensureMore();ensureSheet();const hidden=sources.filter(el=>!isPrimary(el));const sig=hidden.map(x=>(x.id||x.dataset.view||sourceLabel(x))).join('|');if(sig!==signature){signature=sig;const grid=$('mobileMoreGrid');if(grid){grid.innerHTML='';hidden.forEach(src=>{const b=document.createElement('button');b.type='button';b.className='mobile-more-item';b.dataset.source=src.id||src.dataset.view||'';b.innerHTML=`<span>${sourceIcon(src)}</span><b>${sourceLabel(src)}</b>`;b.onclick=()=>{closeSheet();src.click()};grid.appendChild(b)})}}}
function mode(){const mobile=matchMedia('(max-width:820px)').matches;document.body.classList.toggle('mobile-grace-live',mobile&&$('graceLive')?.classList.contains('active'));if(!mobile)closeSheet()}
function activeMore(){const more=$('mobileMoreNav');if(!more)return;const active=navSources().find(x=>x.classList.contains('active'));more.classList.toggle('active',!!active&&!isPrimary(active))}
function init(){viewport();css();buildNav();mode();activeMore();setInterval(()=>{buildNav();mode();activeMore()},650);addEventListener('resize',mode,{passive:true});document.addEventListener('click',e=>{if(e.target.closest('.mobile-more-item'))setTimeout(activeMore,30)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();