(()=>{'use strict';
const C='englishos-grace-v7',P='englishos-translation-preference',$=id=>document.getElementById(id);let bound=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state=()=>{try{return JSON.parse(localStorage.getItem(C)||'{}')}catch{return{}}};
const day=()=>Math.max(1,Math.min(180,Number(state().day||1)));
const pref=()=>localStorage.getItem(P)||'auto';
const mode=()=>pref()!=='auto'?pref():day()<=30?'full':day()<=60?'guided':'off';
const label=()=>({full:'Tradução completa',guided:'Tradução sob demanda',off:'Imersão em inglês'})[mode()];
const desc=()=>pref()!=='auto'?`${label()} escolhida manualmente.`:day()<=30?`Dia ${day()}: traduções e explicações em português ficam mais visíveis.`:day()<=60?`Dia ${day()}: tente entender primeiro e traduza quando precisar. Faltam ${61-day()} dia(s) para a imersão padrão.`:`Dia ${day()}: imersão padrão ativa. O tradutor continua disponível.`;
function text(id,v){const e=$(id),s=String(v??'');if(e&&e.textContent!==s)e.textContent=s}
function styles(){if($('tm2styles'))return;const s=document.createElement('style');s.id='tm2styles';s.textContent=`
.translation-nav{border:0;background:transparent;color:var(--muted);display:flex;align-items:center;gap:10px;padding:10px 12px;border-radius:12px;width:100%;font:inherit;cursor:pointer}.translation-nav:hover,.translation-nav.active{background:var(--brand-soft);color:var(--text)}
.translation-banner{display:flex;justify-content:space-between;gap:14px;align-items:center;margin:0 0 16px;padding:15px 17px;border:1px solid var(--line);border-radius:18px;background:var(--panel);box-shadow:var(--shadow)}.translation-banner b{display:block}.translation-banner small{color:var(--muted)}
.translator-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.translator-output{min-height:230px}.translated-main{font-size:1.08rem;line-height:1.65}.translated-note{margin-top:12px;padding:11px;border-radius:11px;background:var(--panel-2);color:var(--muted);line-height:1.5}
.translation-inline{margin:8px 0 14px}.translation-inline button,.msg-translate{border:1px solid var(--line);background:var(--panel-2);color:var(--text);border-radius:10px;padding:7px 10px;font-weight:800;cursor:pointer}.translation-result{display:none;margin-top:8px;padding:11px;border-left:4px solid var(--brand-2);background:var(--panel-2);border-radius:10px}.translation-result.show{display:block}.msg-translate{display:block;margin-top:6px;border:0;background:transparent;color:var(--brand-2);padding:2px}.msg-result{display:block;margin-top:7px;padding:9px;border-radius:10px;background:var(--brand-soft)}
.translation-fab{position:fixed;right:20px;bottom:20px;z-index:900;border:0;border-radius:999px;padding:13px 17px;background:linear-gradient(135deg,var(--brand),var(--brand-2));color:#fff;font-weight:900;box-shadow:0 14px 35px rgba(31,87,132,.28);cursor:pointer}.translation-setting-status{margin:10px 0;padding:11px;border-radius:11px;background:var(--panel-2);color:var(--muted)}
@media(max-width:800px){.translator-grid{grid-template-columns:1fr}.translation-banner{align-items:flex-start;flex-direction:column}.translation-banner button{width:100%}}`;document.head.appendChild(s)}
function view(){if($('translator'))return;const m=document.querySelector('.main-content');if(!m)return;const v=document.createElement('section');v.id='translator';v.className='view';v.innerHTML=`<div class="section-heading"><div><div class="eyebrow">APOIO BILÍNGUE</div><h2>Tradutor da Grace</h2><p>Português e inglês com explicação, contexto e versão mais simples.</p></div><span class="status-pill" id="translationBadge"></span></div><div class="translator-grid"><article class="card"><label class="field-label">Texto</label><textarea id="translationSource" placeholder="Cole uma frase, mensagem, e-mail ou trecho da aula..."></textarea><label class="field-label">Destino</label><select id="translationTarget"><option value="auto">Detectar automaticamente</option><option value="pt-BR">Português</option><option value="en-US">Inglês</option></select><div class="button-row"><button class="primary" id="runTranslation">Traduzir com a Grace</button><button class="secondary" id="clearTranslation">Limpar</button></div></article><article class="card translator-output" id="translationOutput"><div class="eyebrow">RESULTADO</div><p>A tradução natural aparecerá aqui.</p></article></div><div class="section-heading"><div><div class="eyebrow">PROGRESSÃO</div><h2>Ajuda que diminui até o dia 60</h2></div></div><div class="three-column"><article class="card"><b>Dias 1–30</b><p>Tradução mais visível.</p></article><article class="card"><b>Dias 31–60</b><p>Tradução sob demanda.</p></article><article class="card"><b>Dia 61+</b><p>Imersão com tradutor disponível.</p></article></div>`;m.insertBefore(v,$('settings')||null)}
function nav(){if($('translationNav'))return;const n=document.querySelector('.nav');if(!n)return;const b=document.createElement('button');b.id='translationNav';b.className='translation-nav';b.innerHTML='<span>🌐</span><b>Tradutor</b>';n.insertBefore(b,n.querySelector('[data-view="settings"]')||null);b.onclick=open}
function open(){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='translator'));document.querySelectorAll('.nav-button').forEach(b=>b.classList.remove('active'));$('translationNav')?.classList.add('active');text('todayLabel','APOIO BILÍNGUE');text('pageTitle','Tradutor da Grace');text('pageSubtitle','Entenda o inglês sem depender para sempre do português.');labels();window.scrollTo({top:0,behavior:'smooth'})}
function settings(){if($('translationSettingsCard'))return;const g=document.querySelector('#settings .settings-grid');if(!g)return;const c=document.createElement('article');c.className='card';c.id='translationSettingsCard';c.innerHTML=`<h3>Tradução e português</h3><label class="field-label">Nível de ajuda</label><select id="translationPreference"><option value="auto">Automático até o dia 60</option><option value="full">Completo</option><option value="guided">Sob demanda</option><option value="off">Imersão</option></select><div class="translation-setting-status" id="translationSettingStatus"></div><button class="secondary full" id="openTranslatorSettings">Abrir tradutor</button>`;g.appendChild(c);$('translationPreference').value=pref();$('translationPreference').onchange=e=>{localStorage.setItem(P,e.target.value);help();labels()};$('openTranslatorSettings').onclick=open}
function banner(){if($('translationBanner'))return;const m=document.querySelector('#dashboard .metrics-grid');if(!m)return;const b=document.createElement('div');b.id='translationBanner';b.className='translation-banner';b.innerHTML='<div><b id="translationTitle"></b><small id="translationDescription"></small></div><button class="secondary" id="translationOpen">Abrir tradutor</button>';m.insertAdjacentElement('afterend',b);$('translationOpen').onclick=open}
function fab(){if($('translationFab'))return;const b=document.createElement('button');b.id='translationFab';b.className='translation-fab';b.textContent='🌐 Traduzir';b.onclick=()=>{const s=String(window.getSelection?.()||'').trim();open();if(s)$('translationSource').value=s;$('translationSource')?.focus()};document.body.appendChild(b)}
function help(){const s=$('conversationHelp');if(!s)return;const v=mode()==='full'?'high':mode()==='guided'?'medium':'low';if(s.value!==v)s.value=v}
function labels(){text('translationTitle',`${label()} ativa`);text('translationDescription',desc());text('translationBadge',`Dia ${day()} • ${label()}`);text('translationSettingStatus',desc());if($('translationPreference')&&$('translationPreference').value!==pref())$('translationPreference').value=pref()}
async function translate(t,target='auto',context='tradutor'){const clean=String(t||'').trim();if(!clean)throw Error('Digite ou selecione um texto.');if(!window.GraceAI?.ask)throw Error('A Grace ainda está carregando.');const r=await window.GraceAI.ask('translation',{text:clean.slice(0,8000),target,context,day:day(),translation_mode:mode()});if(!r)throw Error('A tradução não respondeu. Confira a conexão da Grace.');return r}
function result(el,r){const main=r.translation||r.reply||r.improved_answer||'Tradução não retornada.';const simple=r.reply&&r.reply!==main?r.reply:'';const exp=r.explanation||r.feedback||'';el.innerHTML=`<div class="eyebrow">TRADUÇÃO NATURAL</div><div class="translated-main">${esc(main)}</div>${simple?`<div class="translated-note"><b>Versão simples:</b><br>${esc(simple)}</div>`:''}${exp?`<div class="translated-note"><b>Explicação:</b><br>${esc(exp)}</div>`:''}`}
function bind(){const b=$('runTranslation');if(!b||b.dataset.bound)return;b.dataset.bound='1';b.onclick=async()=>{const o=$('translationOutput');b.disabled=true;text('runTranslation','Traduzindo...');try{result(o,await translate($('translationSource').value,$('translationTarget').value,'central de tradução'))}catch(e){o.innerHTML=`<p>${esc(e.message)}</p>`}finally{b.disabled=false;text('runTranslation','Traduzir com a Grace')}};$('clearTranslation').onclick=()=>{$('translationSource').value='';$('translationOutput').innerHTML='<div class="eyebrow">RESULTADO</div><p>A tradução natural aparecerá aqui.</p>'}}
function readable(e){const c=e.cloneNode(true);c.querySelectorAll('button,.translation,.correction,.translation-inline,.msg-result').forEach(n=>n.remove());return c.textContent.replace(/\s+/g,' ').trim()}
function inline(id,context){const t=$(id);if(!t||document.querySelector(`[data-tr-for="${id}"]`))return;const d=document.createElement('div');d.className='translation-inline';d.dataset.trFor=id;d.innerHTML='<button type="button">🌐 Traduzir / explicar</button><div class="translation-result"></div>';t.insertAdjacentElement('afterend',d);const b=d.querySelector('button'),o=d.querySelector('div');b.onclick=async()=>{const x=readable(t);if(!x)return;b.disabled=true;b.textContent='Traduzindo...';o.classList.add('show');o.textContent='A Grace está preparando a tradução...';try{const r=await translate(x,'pt-BR',context);o.innerHTML=`<b>${esc(r.translation||r.reply||'')}</b>${r.explanation?`<br><small>${esc(r.explanation)}</small>`:''}`}catch(e){o.textContent=e.message}finally{b.disabled=false;b.textContent='🌐 Traduzir / explicar'}}}
function messages(){$('conversationChat')?.querySelectorAll('.message.grace:not([data-tr-ready])').forEach(m=>{m.dataset.trReady='1';if(m.querySelector('.translation'))return;const b=document.createElement('button');b.className='msg-translate';b.textContent='🌐 Ver tradução';b.onclick=async()=>{const old=m.querySelector('.msg-result');if(old){old.remove();b.textContent='🌐 Ver tradução';return}b.disabled=true;b.textContent='Traduzindo...';try{const r=await translate(readable(m).replace('🌐 Ver tradução',''),'pt-BR','conversa');const x=document.createElement('span');x.className='msg-result';x.textContent=r.translation||r.reply||'';m.appendChild(x);b.textContent='Ocultar tradução'}catch(e){b.textContent=e.message}finally{b.disabled=false}};m.appendChild(b)})}
function events(){if(bound)return;bound=true;document.addEventListener('click',e=>{if(e.target.closest('.nav-button'))$('translationNav')?.classList.remove('active')})}
function sync(){styles();view();nav();settings();banner();fab();bind();events();help();labels();inline('teacherContent','aula da Grace');inline('grammarExample','gramática');inline('transcript','transcrição');inline('pronunciationTarget','pronúncia');inline('assessmentPrompt','avaliação');messages()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync);else sync();setInterval(sync,2500);
})();