(()=>{'use strict';
const $=id=>document.getElementById(id),P='englishos-voice-vad',G='englishos-guided-path-v1';let cap=null,hands=false,timer=null,obs=null;
const pref=()=>{try{return JSON.parse(localStorage.getItem(P)||'{}')}catch{return{}}},save=v=>localStorage.setItem(P,JSON.stringify({...pref(),...v}));
const b64=b=>new Promise((r,j)=>{const f=new FileReader();f.onload=()=>r(String(f.result).split(',')[1]||'');f.onerror=j;f.readAsDataURL(b)});
const mime=()=>['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported?.(t))||'';
function visual(on,level=0){const s=$('live2Stage');s?.classList.toggle('voice-sensing',on);s?.style.setProperty('--voice-level',String(level));$('futureStopVoice')?.classList.toggle('visible',on)}
async function transcribe(blob){const r=await fetch('/api/stt',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({audioBase64:await b64(blob),mimeType:blob.type})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Não consegui entender sua fala.');return d}
async function listen(btn){if(cap)throw Error('O microfone já está ativo.');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Use Chrome ou Edge atualizado e permita o microfone.');
 const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}}),AC=window.AudioContext||window.webkitAudioContext,ac=new AC(),src=ac.createMediaStreamSource(stream),an=ac.createAnalyser();an.fftSize=1024;src.connect(an);const a=new Float32Array(an.fftSize),chunks=[],m=mime(),rec=m?new MediaRecorder(stream,{mimeType:m}):new MediaRecorder(stream);let raf,start=performance.now(),spoken=false,last=0,noise=0,n=0,thr=.018,why='silence';
 visual(true);btn?.classList.add('voice-sensing');$('futureInputState')&&($('futureInputState').textContent='Listening');
 const clean=()=>{cancelAnimationFrame(raf);stream.getTracks().forEach(t=>t.stop());src.disconnect();an.disconnect();ac.close().catch(()=>{});visual(false);btn?.classList.remove('voice-sensing');cap=null};
 const stop=w=>{why=w;if(rec.state==='recording')rec.stop()};cap={stop};
 const done=new Promise((resolve,reject)=>{rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onerror=()=>{clean();reject(Error('Falha ao gravar o áudio.'))};rec.onstop=async()=>{clean();try{if(!spoken&&why!=='manual')throw Error('Não detectei fala. Tente novamente um pouco mais perto do microfone.');const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});if(blob.size<700)throw Error('A fala ficou curta demais.');$('futureInputState')&&($('futureInputState').textContent='Transcribing');resolve(await transcribe(blob))}catch(e){reject(e)}}});rec.start(180);
 const loop=now=>{an.getFloatTimeDomainData(a);let sum=0;for(const v of a)sum+=v*v;const rms=Math.sqrt(sum/a.length),el=now-start;if(el<450){noise+=rms;n++;if(n>4)thr=Math.max(.012,noise/n*2.8)}const level=Math.max(0,Math.min(1,(rms-thr)/Math.max(.035,thr*4)));visual(true,level);if(rms>thr&&el>180){spoken=true;last=now}if(spoken&&now-last>900&&el>700){stop('silence');return}if(!spoken&&el>6500){stop('no-speech');return}if(el>22000){stop('max');return}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return done}
function show(d){const e=$('futureTranscript');if(!e)return;const ws=Array.isArray(d.words)?d.words.slice(-18):[];e.innerHTML=`<b>Você disse:</b> ${d.text||''}${ws.length?'<div class="future-words">'+ws.map(w=>`<span>${w.word||''}</span>`).join('')+'</div>':''}`}
function fmt(ai){return [ai?.feedback,ai?.correction&&`Correção: ${ai.correction}`,ai?.explanation,ai?.reply&&`Grace: ${ai.reply}`,ai?.translation&&`Tradução: ${ai.translation}`,ai?.score!=null&&`Pontuação: ${ai.score}/100`].filter(Boolean).join('\n')||'Prática registrada.'}
function saveRepeat(c,text,ai){let s;try{s=JSON.parse(localStorage.getItem(G)||'{}')}catch{s={}}s.steps=s.steps||{};const d=s.steps[c.day]=s.steps[c.day]||{step:2,done:[],attempts:{}};d.attempts=d.attempts||{};d.attempts.repeat=`Você falou: ${text}\n${fmt(ai)}`;d.done=Array.isArray(d.done)?d.done:[];if(!d.done.includes(2))d.done.push(2);d.step=3;localStorage.setItem(G,JSON.stringify(s))}
async function live(btn){if(cap){cap.stop('manual');return}btn.disabled=true;btn.textContent='■';try{const d=await listen(btn);show(d);$('live2Text').value=d.text;btn.disabled=false;btn.textContent='🎙️';$('live2Send')?.click()}catch(e){btn.disabled=false;btn.textContent='🎙️';$('live2Caption')&&($('live2Caption').textContent=e.message);if(hands){hands=false;save({hands:false});hud()}}}
async function guided(btn,type){if(cap){cap.stop('manual');return}btn.disabled=true;btn.textContent='■ Ouvindo';const out=$('guidedResult');out?.classList.remove('hidden');try{const d=await listen(btn);show(d);const c=window.EnglishOSGuided?.getContext?.();if(type==='speak'){$('guidedAnswer').value=d.text;btn.disabled=false;$('guidedCheck')?.click();return}const ai=await window.GraceAI.ask('guided_lesson',{stage:'repeat',day:c.day,module:c.module,goal:c.goal,grammar:c.grammar,target:c.target,translation:c.translation,cue:c.cue,help:c.help,transcript:d.text});saveRepeat(c,d.text,ai);window.EnglishOSGuided.open()}catch(e){if(out)out.textContent=e.message}finally{btn.disabled=false;btn.textContent=type==='speak'?'🎙️ Responder falando':'🎙️ Falar novamente'}}
function hud(){const b=$('futureHandsFree');if(b){b.classList.toggle('active',hands);b.textContent=`∞ Fluxo contínuo: ${hands?'ON':'OFF'}`}$('futureFlowState')&&($('futureFlowState').textContent=hands?'Hands-free':'Manual')}
function bindControls(){const b=$('futureHandsFree');if(b&&!b.dataset.engine){b.dataset.engine='1';b.onclick=()=>{hands=!hands;save({hands});hud();if(!hands)clearTimeout(timer)}}const s=$('futureStopVoice');if(s&&!s.dataset.engine){s.dataset.engine='1';s.onclick=()=>{hands=false;save({hands:false});hud();clearTimeout(timer);cap?.stop('manual')}}}
function schedule(){clearTimeout(timer);if(!hands||cap||document.hidden)return;timer=setTimeout(()=>{const b=$('live2Mic');if(b&&!b.disabled)live(b)},650)}
function init(){hands=Boolean(pref().hands);document.addEventListener('click',e=>{const l=e.target.closest?.('#live2Mic');if(l){e.preventDefault();e.stopImmediatePropagation();live(l);return}const r=e.target.closest?.('#guidedRecord');if(r){e.preventDefault();e.stopImmediatePropagation();guided(r,'repeat');return}const s=e.target.closest?.('#guidedSpeak');if(s){e.preventDefault();e.stopImmediatePropagation();guided(s,'speak');return}},true);setInterval(()=>{bindControls();if(!obs&&$('live2State')){obs=new MutationObserver(()=>{if(hands&&/sua vez/i.test($('live2State').textContent||''))schedule()});obs.observe($('live2State'),{childList:true,subtree:true})}hud()},700);document.addEventListener('visibilitychange',()=>{if(document.hidden&&cap)cap.stop('manual')});window.GraceVoiceVAD={listen,stop:()=>cap?.stop('manual')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();